// Tlumaczenie interfejsu Szybkiego Dostepu (VELIVO_LANG ustawia Velivo w jezyk-wybor.js).
var SD_SLOWNIK = {
"most rozlaczony": "bridge disconnected",
"wyjatek przy laczeniu: ": "exception while connecting: ",
"brak odpowiedzi mostu (limit czasu)": "no bridge response (timeout)",
"blad wysylki: ": "send error: ",
"Z drugiego komputera: bylo ": "From the other computer: there were ",
" skrotow, jest ": " shortcuts, now ",
"PIN dla profilu \"": "PIN for profile \"",
"Zostaw puste, zeby zdjac PIN. Kod bedzie potrzebny przy kazdym wejsciu w ten profil.": "Leave empty to remove the PIN. The code will be needed every time you open this profile.",
"PIN zdjety z profilu \"": "PIN removed from profile \"",
"Profil \"": "Profile \"",
"\" jest teraz na PIN. Zapamietaj kod - nie da sie go odzyskac.": "\" is now PIN-protected. Remember the code – it cannot be recovered.",
"\" jest na PIN": "\" is PIN-protected",
"Podaj kod, zeby wejsc.": "Enter the code to open it.",
"Zly PIN - profil nie zostal otwarty.": "Wrong PIN – the profile was not opened.",
"Profil: ": "Profile: ",
" (na PIN)": " (PIN)",
"Nazwa nowego profilu:": "New profile name:",
"\" juz istnieje.": "\" already exists.",
"Nowy profil \"": "New profile \"",
"\" - zaczyna od pustej tablicy. Dane leza w dane\\\\profil-": "\" – starts with an empty board. Data is in dane\\\\profil-",
"Profilu domyslnego nie da sie przemianowac - jego dane leza wprost w dane\\\\.": "The default profile cannot be renamed – its data is directly in dane\\\\.",
"Nowa nazwa profilu \"": "New name for profile \"",
"Taki profil juz istnieje.": "Such a profile already exists.",
"Zmiana nazwy wymaga przeniesienia folderu dane\\\\profil-": "Renaming requires moving the folder dane\\\\profil-",
" na dane\\\\profil-": " to dane\\\\profil-",
". Zrob to w Eksploratorze, potem wroc tutaj.": ". Do it in File Explorer, then come back here.",
"Profilu domyslnego nie da sie usunac.": "The default profile cannot be deleted.",
"Usunac profil \"": "Remove profile \"",
"\" z listy?\\n\\n": "\" from the list?\\n\\n",
"Jego zakladki i ikony ZOSTAJA na dysku w folderze dane\\\\profil-": "Its shortcuts and icons STAY on disk in the folder dane\\\\profil-",
"Nic nie jest kasowane - profil po prostu znika z przelacznika.": "Nothing is deleted – the profile just disappears from the switcher.",
"\" zdjety z listy. Pliki zostaly w dane\\\\profil-": "\" removed from the list. Files stayed in dane\\\\profil-",
"+ Nowy profil...": "+ New profile...",
"Wczytano nowsza wersje z konta Google.": "Loaded a newer version from the Google account.",
"Scalono z wspolnym plikiem: bylo ": "Merged with the shared file: there were ",
"Tablica jest pusta, ale na Twoim koncie Google lezy kopia: ": "The board is empty, but there is a copy in your Google account: ",
" skrotow w ": " shortcuts in ",
" grupach. Przywrocic?": " groups. Restore?",
"Przywroc": "Restore",
"Przywrocono ": "Restored ",
" skrotow z konta Google. Ikony pobiora sie same - ": " shortcuts from the Google account. Icons will download by themselves – ",
"obrazki nie miescilyby sie w limicie konta i nie sa tam trzymane.": "images would not fit in the account limit and are not kept there.",
"Nie teraz": "Not now",
"Synchronizacja: przez Velivo (siec lokalna LAN)": "Sync: via Velivo (local network LAN)",
"Synchronizacja: brak konta w przegladarce - dane zostaja lokalnie": "Sync: no browser account – data stays local",
"Synchronizacja z kontem Google: wylaczona": "Sync with Google account: off",
"Synchronizacja: WLACZONA dla ": "Sync: ON for ",
"konta w tej przegladarce": "the account in this browser",
"Synchronizacja: WLACZONA (nie wiem, na jakim koncie)": "Sync: ON (account unknown)",
"Konto Google zapelnia sie: zajete ": "The Google account is filling up: used ",
"% ze 100 KB (": "% of 100 KB (",
" skrotow). Zmiesci sie jeszcze okolo ": " shortcuts). About this many more will fit: ",
"Gdy zabraknie miejsca, skroty i tak zostana na dysku - przestana tylko ": "When space runs out, shortcuts stay on disk anyway – they just stop ",
"wedrowac miedzy komputerami.": "travelling between computers.",
"Rozumiem": "Got it",
"Konto Google jest pelne (limit 100 KB, ustala go Google i nie da sie go podniesc). ": "The Google account is full (100 KB limit set by Google, cannot be raised). ",
"Twoje skroty SA BEZPIECZNE - zapis na dysku sie udal, nie wedruja tylko na inne komputery. ": "Your shortcuts ARE SAFE – saving to disk worked, they just don't travel to other computers. ",
"Pomoze oproznienie kosza albo usuniecie nieuzywanych skrotow.": "Emptying the trash or removing unused shortcuts will help.",
"Nie udalo sie zapisac do konta Google: ": "Could not save to the Google account: ",
" (zapis lokalny sie udal)": " (local save worked)",
"Ta przegladarka nie udostepnia wyboru folderu, wiec nie moze ZAPISYWAC do wspolnego pliku. ": "This browser does not offer folder selection, so it cannot WRITE to the shared file. ",
"Skroty i ikony nadal sie wczytuja przy starcie. W Brave sprobuj: brave://flags > \"File System Access API\" > Enabled.": "Shortcuts and icons still load at startup. In Brave try: brave://flags > \"File System Access API\" > Enabled.",
"Brak zgody na zapis w folderze.": "No permission to write to the folder.",
"Podlaczono folder \"": "Connected folder \"",
"Nie udalo sie podlaczyc folderu: ": "Could not connect the folder: ",
"Naprawiono ": "Fixed ",
" ikon nienalezacych do swoich stron - pobiora sie na nowo.": " icons that did not belong to their pages – they will download again.",
"Przywrocono \"": "Restored \"",
"\" do grupy ": "\" to group ",
"Utworzono wspolny plik z biezaca zawartoscia.": "Created the shared file with the current content.",
"Scalono zmiany ze wspolnego pliku.": "Merged changes from the shared file.",
"Wyslano scalona wersje do wspolnego pliku.": "Sent the merged version to the shared file.",
"Wspolny plik czeka na zgode. Przegladarka kasuje ja po zamknieciu, ": "The shared file is waiting for permission. The browser clears it when closed, ",
"wiec pytam raz na jej uruchomienie. Jesli w oknie zgody bedzie opcja ": "so I ask once per browser start. If the permission window offers ",
"\"Zezwalaj przy kazdej wizycie\" - zaznacz ja.": "\"Allow on every visit\" – select it.",
"Zezwol i zsynchronizuj": "Allow and sync",
"Polaczono - obie wersje sa identyczne.": "Connected – both versions are identical.",
"Bez zgody wymiana przez plik nie zadziala.": "Without permission, file exchange will not work.",
"Przerwane - bez podlaczonego folderu nie zapisze ikon jako plikow.": "Stopped – without a connected folder icons cannot be saved as files.",
"Pobieram ikony (": "Downloading icons (",
"Gotowe: ": "Done: ",
" ikon zapisano jako pliki w dane\\\\ikony, ": " icons saved as files in dane\\\\ikony, ",
" stron nie udostepnia ikony pod standardowym adresem.": " sites do not offer an icon at the standard address.",
"Bez zgody na dostep do witryn zapisalem tylko adresy ": "Without site access permission I only saved the addresses of ",
" ikon (nie stana sie plikami). Brak ikony: ": " icons (they will not become files). No icon: ",
"Przeniesiono \"": "Moved \"",
"Chrome blokuje otwieranie \"": "Chrome blocks opening \"",
"\" z linku. Adres skopiowano - wklej go w pasek adresu.": "\" from a link. The address was copied – paste it into the address bar.",
"Ten adres trzeba wpisac recznie w pasku adresu: ": "This address must be typed manually in the address bar: ",
"Edytuj": "Edit",
"Usun": "Delete",
"Usunieto \"": "Deleted \"",
"\". Mozna cofnac.": "\". You can undo.",
"Cofnij": "Undo",
"Sync OK: ": "Sync OK: ",
"Most obsluguje folder:\\n": "The bridge serves the folder:\\n",
"\\n\\nJesli to NIE jest folder tego rozszerzenia, uruchom w nim INSTALUJ.bat.": "\\n\\nIf this is NOT this extension's folder, run INSTALUJ.bat in it.",
"Wymiana danych z folderem dziala. Zmiany z innych komputerow przychodza co 5 sekund.": "Data exchange with the folder works. Changes from other computers arrive every 5 seconds.",
"Tylko odczyt": "Read only",
"Ta przegladarka nie udostepnia wyboru folderu (np. Brave z wylaczonym File System Access API). ": "This browser does not offer folder selection (e.g. Brave with File System Access API disabled). ",
"Skroty i ikony wczytuja sie przy starcie, ale zmiany zrobione tutaj nie trafia do pozostalych komputerow.": "Shortcuts and icons load at startup, but changes made here will not reach other computers.",
"Sync: kliknij, aby wznowic": "Sync: click to resume",
"Zgoda na zapis wygasla po zamknieciu przegladarki. Jedno klikniecie ja przywroci.": "Write permission expired when the browser closed. One click restores it.",
"BRAK SYNCHRONIZACJI - kliknij": "NO SYNC – click",
"Folder nie jest podlaczony. Ta przegladarka nie wymienia sie danymi z pozostalymi.": "The folder is not connected. This browser does not exchange data with the others.",
"Nie udalo sie wczytac obrazka": "Could not load the image",
"Przerwane - folder rozszerzenia nie zostal podlaczony.": "Stopped – the extension folder was not connected.",
"Nie udalo sie utworzyc podfolderu dane\\\\ikony.": "Could not create the subfolder dane\\\\ikony.",
"Porzadkuje: ": "Tidying up: ",
"Uporzadkowane. Przeniesiono ": "Tidied up. Moved ",
" ikon do plikow": " icons to files",
" sie nie udalo": " failed",
", usunieto ": ", deleted ",
" KB.": " KB.",
"Dograno ": "Added ",
" ikon do dane\\\\ikony (Chrome poznal je po odwiedzeniu stron).": " icons to dane\\\\ikony (the browser learned them after visiting the pages).",
"Bez podlaczonego folderu nie zapisze ikon jako plikow.": "Without a connected folder icons cannot be saved as files.",
"Pobieram brakujace ikony: ": "Downloading missing icons: ",
"Szukam ikony: ": "Looking for icon: ",
"Uzupelniono ikony: ": "Icons added: ",
" z pamieci przegladarki, ": " from browser memory, ",
" pobranych z witryn.": " downloaded from websites.",
"Nie udalo sie znalezc ikon dla tych stron - mozesz wstawic wlasny obrazek przy edycji kafelka.": "Could not find icons for these sites – you can set your own image when editing the tile.",
"Przerwane - bez podlaczonego folderu ikony nie moga stac sie plikami.": "Stopped – without a connected folder icons cannot become files.",
"Osadzam ikony (": "Embedding icons (",
"Ikony: ": "Icons: ",
" zapisano jako pliki w podfolderze \"ikony\", ": " saved as files in the \"ikony\" subfolder, ",
" wpisano do danych, pominieto ": " written into data, skipped ",
" (Chrome nie zna ich ikon).": " (the browser does not know their icons).",
"Edytuj skrot": "Edit shortcut",
"Nowy skrot": "New shortcut",
"Nie udalo sie wczytac obrazka: ": "Could not load the image: ",
"Wklejono obrazek jako ikone.": "Image pasted as the icon.",
"Nie udalo sie wkleic obrazka: ": "Could not paste the image: ",
"Ikone zapisano jako plik w dane\\\\ikony - powedruje z folderem.": "Icon saved as a file in dane\\\\ikony – it will travel with the folder.",
"Ikone zapisano w danych. Podlacz folder rozszerzenia, zeby trafiala do pliku.": "Icon saved in data. Connect the extension folder to save it as a file.",
"Uporzadkowano: usunieto ": "Tidied up: deleted ",
" niepotrzebny plik ikony.": " unneeded icon file.",
"Nazwa nowej grupy:": "New group name:",
"Synchronizacja wznowiona.": "Sync resumed.",
"Zapisano w ": "Saved in ",
"Zapisano do wskazanego pliku.": "Saved to the chosen file.",
"Zapisano do folderu pobierania. Podlacz folder rozszerzenia, zeby kopia trafiala od razu obok programu.": "Saved to the downloads folder. Connect the extension folder to put the copy right next to the program.",
"Nazwa tego komputera (uzywana w nazwach kopii zapasowych):": "Name of this computer (used in backup names):",
"Kopia zapisana jako ": "Backup saved as ",
"Nazwa zapisana. Kopia powstanie, gdy folder bedzie podlaczony.": "Name saved. The backup will be made when the folder is connected.",
"Najpierw nadaj nazwe temu komputerowi.": "First give this computer a name.",
"Kopia zapasowa zapisana w dane\\\\kopie.": "Backup saved in dane\\\\kopie.",
"Nie udalo sie zapisac kopii - sprawdz folder.": "Could not save the backup – check the folder.",
"Rozszerzenie nie ma teraz dostepu do witryn.": "The extension has no site access now.",
"Cofnieto dostep do witryn. Ikony juz zapisane jako pliki zostaja.": "Site access revoked. Icons already saved as files stay.",
"Nie udalo sie cofnac: ": "Could not revoke: ",
"Usunieto ": "Deleted ",
" przypisan i ": " assignments and ",
" plikow PNG z dane\\\\ikony.": " PNG files from dane\\\\ikony.",
"W Velivo skroty, grupy i ikony synchronizuje sama przegladarka przez siec lokalna (LAN) - ": "In Velivo, shortcuts, groups and icons are synced by the browser itself over the local network (LAN) – ",
"Ustawienia Velivo > Synchronizacja w czasie rzeczywistym. Konto Google nie jest potrzebne.": "Velivo Settings > Real-time sync. No Google account is needed.",
"Synchronizacja wlaczona": "Sync on",
" dla ": " for ",
" - wyslano ": " – sent ",
" KB na konto.": " KB to the account.",
"Nie udalo sie wlaczyc synchronizacji: ": "Could not turn on sync: ",
"Synchronizacja wylaczona, dane usuniete z konta Google.": "Sync off, data removed from the Google account.",
"Bede pytal o zgode raz na uruchomienie przegladarki.": "I will ask for permission once per browser start.",
"Nie bede pytal - synchronizacja tylko przez \"Synchronizuj z plikiem TERAZ\".": "I will not ask – sync only via \"Sync with file NOW\".",
"Folder obsługuje Sejf – nic nie trzeba wybierać.": "The folder is handled by Sejf – nothing to choose.",
"Odlaczyc folder rozszerzenia?\\n\\nIkony przestana sie zapisywac jako pliki PNG.": "Disconnect the extension folder?\\n\\nIcons will stop being saved as PNG files.",
"Folder odlaczony.": "Folder disconnected.",
"Ta przegladarka nie obsluguje wyboru folderu.": "This browser does not support folder selection.",
"\" - porzadkuje strukture...": "\" – tidying up the structure...",
"Najpierw podlacz folder rozszerzenia albo wspolny plik.": "First connect the extension folder or the shared file.",
"Brak zgody na dostep.": "No access permission.",
"Obie wersje sa identyczne - nie bylo czego wymieniac.": "Both versions are identical – nothing to exchange.",
"Wspolny plik: ": "Shared file: ",
"OK     = ODLACZ (skroty zostaja, wymiana sie konczy)\\n": "OK     = DISCONNECT (shortcuts stay, exchange ends)\\n",
"Anuluj = zostaw polaczenie": "Cancel = keep the connection",
"Wspolny plik odlaczony.": "Shared file disconnected.",
"Ta wersja przegladarki nie obsluguje zapisu do wskazanego pliku.": "This browser version does not support writing to a chosen file.",
"Brak zgody na zapis do pliku.": "No permission to write to the file.",
"Wskazany plik zawiera NOWSZA wersje skrotow.\\n\\nOK = wczytaj z pliku\\nAnuluj = nadpisz plik tym, co masz tutaj": "The chosen file contains a NEWER version of the shortcuts.\\n\\nOK = load from the file\\nCancel = overwrite the file with what you have here",
"Polaczono ze wspolnym plikiem. Wskaz ten sam plik w drugim profilu.": "Connected to the shared file. Choose the same file in the other profile.",
"Nie udalo sie polaczyc z plikiem: ": "Could not connect to the file: ",
"Kosz jest pusty.": "The trash is empty.",
"Kosz jest juz pusty.": "The trash is already empty.",
"Oproznic kosz? ": "Empty the trash? ",
" pozycji zniknie na dobre.": " items will be gone for good.",
"Kosz oprozniony.": "Trash emptied.",
"Odswiezono miniatury: ": "Thumbnails refreshed: ",
"Wszystkie skroty maja juz ikony.": "All shortcuts already have icons.",
"NIE DZIALA": "NOT WORKING",
"BRAK (przegladarka nie pozwala wybrac folderu)": "NONE (the browser does not allow choosing a folder)",
"(nie ustawiono)": "(not set)",
"Nowa nazwa grupy:": "New group name:",
"Nie mozna usunac jedynej grupy.": "The only group cannot be deleted.",
"Usunac grupe \"": "Delete group \"",
"\" razem ze skrotami?": "\" together with its shortcuts?",
"Usunieto grupe oraz ": "Deleted the group and ",
" niepotrzebnych plikow ikon.": " unneeded icon files.",
"PIN profilu \"": "PIN of profile \"",
"Usun profil \"": "Delete profile \"",
"% ze 100 KB)": "% of 100 KB)",
"Zajete ": "Used ",
" KB ze 100 KB.\\n": " KB of 100 KB.\\n",
"Skrotow: ": "Shortcuts: ",
", zmiesci sie jeszcze okolo ": ", about this many more will fit: ",
"Wspolny plik na dysku: ": "Shared file on disk: ",
"Folder rozszerzenia: obsluguje most (nic nie trzeba robic)": "Extension folder: handled by the bridge (nothing to do)",
"Folder rozszerzenia: ": "Extension folder: ",
"Kosz... (": "Trash... (",
"Miniatury stron: ": "Page thumbnails: ",
"Nazwa tego komputera: ": "Name of this computer: ",
"Pytanie o zgode do pliku: ": "Ask for file permission: ",
"WYLACZONE (tylko recznie)": "OFF (manual only)",
"raz na uruchomienie": "once per start",
"Nie znalazlem w tym pliku zadnych adresow.\\n\\n": "I found no addresses in this file.\\n\\n",
"Obslugiwane sa: kopie Szybkiego Dostepu, pliki JSON z innych\\n": "Supported: Quick Access backups, JSON files from other\\n",
"speed dialow oraz zakladki wyeksportowane do HTML.": "speed dials and bookmarks exported to HTML.",
"Rozpoznano: ": "Recognized: ",
"Znaleziono ": "Found ",
" grupach.\\n\\n": " groups.\\n\\n",
"OK  = DODAJ do obecnych skrotow\\n": "OK  = ADD to current shortcuts\\n",
"Anuluj = ZASTAP wszystko zawartoscia pliku": "Cancel = REPLACE everything with the file content",
"Na pewno ZASTAPIC wszystkie obecne skroty?": "Really REPLACE all current shortcuts?",
"Zaimportowano ": "Imported ",
" skrotow (": " shortcuts (",
" nieuzywanych ikon": " unused icons",
"Nie udalo sie wczytac pliku: ": "Could not load the file: ",
"Zostan tutaj": "Stay here",
"Wroc na strone": "Back to the page",
"Nie moge wrocic - tamta karta zostala zamknieta.": "Cannot go back – that tab was closed.",
"Dodano \"": "Added \"",
"Jednorazowa konfiguracja: wskaz folder rozszerzenia, a reszta zrobi sie sama.": "One-time setup: choose the extension folder and the rest happens automatically.",
"Skonfiguruj": "Set up",
"Nie pytaj": "Don't ask",
"Dodano nowa strone z menu kontekstowego.": "Added a new page from the context menu.",
"Dodaj do Szybkiego Dostepu": "Add to Quick Access",
"Grupa juz nie istnieje": "The group no longer exists",
"Ta strona juz jest w grupie ": "This page is already in group ",
"Szybki Dostep": "Quick Access",
"Nie udalo sie odczytac adresu": "Could not read the address",
"Nie udalo sie otworzyc okna PIN": "Could not open the PIN window",
"Dodano do grupy ": "Added to group ",
" (profil ": " (profile ",
"Zgloszenie wygaslo - sprobuj jeszcze raz.": "The request expired – try again.",
"Zly PIN.": "Wrong PIN.",
"Brak odpowiedzi sejfu.": "No response from Sejf.",
"Sejf nie odpowiada ramkom wewnatrz strony.": "Sejf does not answer frames inside a page.",
"Tego polecenia strona nie moze wyslac.": "A page cannot send this command.",
"Nieznany adres strony.": "Unknown page address.",
"To nie jest zwykla strona WWW.": "This is not a regular web page.",
"Zapisz": "Save",
"Nie dla tej strony": "Not for this site",
"Zapisuje w zaszyfrowanym sejfie... czekam na potwierdzenie.": "Saving in the encrypted Sejf... waiting for confirmation.",
"Sejf nie odpowiedzial.": "Sejf did not respond.",
"Haslo zaktualizowane w sejfie.": "Password updated in Sejf.",
"Login zapisany w sejfie.": "Login saved in Sejf.",
"OK, zamknij": "OK, close",
"Nie zapisalem: ": "Not saved: ",
"Sprobuj ponownie": "Try again",
"Sejf - wypelnij, wygeneruj haslo, zapisz": "Sejf – fill in, generate password, save",
"Szukam kont w Sejfie...": "Looking for accounts in Sejf...",
"Brak zapisanych kont dla tej strony.": "No saved accounts for this site.",
"(bez loginu)": "(no login)",
"Zapisz wpisane dane w Sejfie": "Save the entered data in Sejf",
"Zapisane w Sejfie (Hasla do stron).": "Saved in Sejf (Website passwords).",
"Ten login juz jest w Sejfie. Po zalogowaniu Sejf zapyta, czy zaktualizowac haslo.": "This login is already in Sejf. After signing in, Sejf will ask whether to update the password.",
"Sejf niedostepny: ": "Sejf unavailable: ",
"Sprawdz, czy Sejf jest zainstalowany z mostem do przegladarek.": "Check that Sejf is installed with the browser bridge.",
"Uzyj tego hasla i zapisz w Sejfie": "Use this password and save it in Sejf",
"Losuj inne": "Generate another",
"Proponowane mocne haslo:": "Suggested strong password:",
"Haslo wpisane. Wpisz login i wyslij formularz - Sejf zapyta o zapis.": "Password entered. Enter the login and submit the form – Sejf will ask to save it.",
"Zapisuje w Sejfie...": "Saving in Sejf...",
"Haslo wpisane i zapisane w Sejfie (Hasla do stron).": "Password entered and saved in Sejf (Website passwords).",
"Haslo wpisane. Ten login juz jest w Sejfie - stare haslo zostaje, dopoki po wyslaniu formularza nie potwierdzisz zmiany.": "Password entered. This login is already in Sejf – the old password stays until you confirm the change after submitting the form.",
"Haslo wpisane, ale Sejf go nie zapisal (": "Password entered, but Sejf did not save it (",
"). Po wyslaniu formularza Sejf zapyta jeszcze raz.": "). After submitting the form Sejf will ask again.",
"Ta strona nie obsluguje logowania.": "This page does not support signing in.",
"Nie udalo sie otworzyc sejfu.": "Could not open Sejf.",
"Brak wpisu typu Login dla tej domeny. W bazie wpisz domene w polu Lokalizacja.": "No Login entry for this domain. In the database, enter the domain in the Location field.",
"Wybierz wpis i wypelnij formularz.": "Choose an entry and fill in the form.",
"Bez nazwy": "Untitled",
"Nie znaleziono pola loginu albo hasla na tej stronie.": "No login or password field found on this page.",
"Formularz wypelniony. Sprawdz dane i zaloguj sie.": "Form filled in. Check the data and sign in.",
"Wpisz login i haslo.": "Enter login and password.",
"Zapisuje wpis w zaszyfrowanym sejfie...": "Saving the entry in the encrypted Sejf...",
"Nie zapisano wpisu.": "The entry was not saved.",
"Nie ma na co czekac - zgloszenie wygaslo.": "Nothing to wait for – the request expired.",
"Podaj kod, zeby dodac te strone do profilu \"": "Enter the code to add this page to profile \"",
"Proces tla nie odpowiada. Zamknij to okno i sprobuj ponownie.": "The background process is not responding. Close this window and try again.",
"Nie udalo sie dodac.": "Could not add.",
"Proces tla nie odpowiada.": "The background process is not responding.",
"(mozesz tez wkleic obrazek: Ctrl+V)": "(you can also paste an image: Ctrl+V)",
"(puste = z adresu)": "(empty = from the address)",
"+ Grupa": "+ Group",
"+ Skrot": "+ Shortcut",
", zeby dodac pierwszy kafelek.": " to add the first tile.",
"Adres": "Address",
"Anuluj": "Cancel",
"Bardzo duze": "Very large",
"Cofnij dostep do witryn": "Revoke site access",
"Czern (OLED)": "Black (OLED)",
"Dodaj grupe": "Add group",
"Dodaj skrot": "Add shortcut",
"Duze": "Large",
"Filtruj skroty...": "Filter shortcuts...",
"Folder rozszerzenia: ...": "Extension folder: ...",
"Grafit": "Graphite",
"Granat": "Navy",
"Ikona": "Icon",
"Kod": "Code",
"Kosz": "Trash",
"Kosz...": "Trash...",
"Las": "Forest",
"Male kafelki": "Small tiles",
"Mgla": "Mist",
"Miniatury stron: ...": "Page thumbnails: ...",
"Nazwa": "Name",
"Nazwa tego komputera: ...": "Name of this computer: ...",
"Nocny fiolet": "Night violet",
"Nowa karta": "New tab",
"Ogromne": "Huge",
"Oproznij kosz": "Empty trash",
"PIN tego profilu: ...": "PIN of this profile: ...",
"Papier": "Paper",
"Pomoc i informacje": "Help and information",
"Potwierdz": "Confirm",
"Profil": "Profile",
"Pytanie o zgode: ...": "Permission prompt: ...",
"Rozmiar kafelkow": "Tile size",
"Srednie": "Medium",
"Stan synchronizacji": "Sync status",
"Synchronizacja z kontem Google: ...": "Sync with Google account: ...",
"Synchronizuj z plikiem teraz": "Sync with file now",
"Ta grupa jest pusta. Kliknij": "This group is empty. Click",
"Tlo": "Background",
"Tlo: systemowe": "Background: system",
"Uporzadkuj folder": "Tidy up folder",
"Usun biezaca grupe": "Delete current group",
"Usun ten profil": "Delete this profile",
"Usun wlasna": "Remove custom",
"Usun wszystkie ikony": "Delete all icons",
"Uzupelnij brakujace ikony": "Fill in missing icons",
"Wczytaj kopie z pliku...": "Load backup from file...",
"Wiecej": "More",
"Wspolny plik (stary sposob): ...": "Shared file (old method): ...",
"Wybierz obrazek...": "Choose image...",
"Zaawansowane...": "Advanced...",
"Zachod slonca": "Sunset",
"Zamknij": "Close",
"Zapisz kopie teraz": "Save backup now",
"Zmien nazwe biezacej grupy": "Rename current group",
"Zrob kopie zapasowa teraz": "Make a backup now",
"Dodaj login": "Add login",
"Haslo": "Password",
"Login lub e-mail": "Login or e-mail",
"Nie ma wpisu? Dodaj login do zaszyfrowanego sejfu.": "No entry? Add a login to the encrypted Sejf.",
"Sprawdzam strone...": "Checking the page...",
"Szukam loginow.": "Looking for logins.",
"Szybki Dostep - Sejf": "Quick Access – Sejf",
"Wypelnij formularz": "Fill in the form",
"Dodaj": "Add",
"PIN profilu": "Profile PIN",
"Podaj kod, zeby dodac strone do tego profilu.": "Enter the code to add the page to this profile.",
"Profil na PIN": "PIN-protected profile",
"Start": "Start",
"Domyslny": "Default"
};
var SD_KLUCZE = Object.keys(SD_SLOWNIK).filter(function (k) { return k.trim().length >= 12; }).sort(function (a, b) { return b.length - a.length; });
function SD_T(s) {
  if (typeof VELIVO_LANG === 'undefined' || VELIVO_LANG !== 'en' || typeof s !== 'string' || !s) return s;
  if (Object.prototype.hasOwnProperty.call(SD_SLOWNIK, s)) return SD_SLOWNIK[s];
  var t = s.trim();
  if (t && Object.prototype.hasOwnProperty.call(SD_SLOWNIK, t)) return s.replace(t, SD_SLOWNIK[t]);
  var w = s;
  for (var i = 0; i < SD_KLUCZE.length; i++) if (w.indexOf(SD_KLUCZE[i]) >= 0) w = w.split(SD_KLUCZE[i]).join(SD_SLOWNIK[SD_KLUCZE[i]]);
  return w;
}
(function () {
  if (typeof document === 'undefined' || typeof VELIVO_LANG === 'undefined' || VELIVO_LANG !== 'en' || location.protocol !== 'chrome-extension:') return;
  try { document.documentElement.lang = 'en'; } catch (e) {}
  var ATR = ['title', 'placeholder', 'aria-label'];
  function el(n) {
    if (n.nodeType === 3) { var v = SD_T(n.nodeValue); if (v !== n.nodeValue) n.nodeValue = v; return; }
    if (n.nodeType !== 1 || n.tagName === 'SCRIPT' || n.tagName === 'STYLE' || n.tagName === 'TEXTAREA') return;
    for (var i = 0; i < ATR.length; i++) { var a = n.getAttribute(ATR[i]); if (a) { var b = SD_T(a); if (b !== a) n.setAttribute(ATR[i], b); } }
    if ((n.tagName === 'INPUT') && (n.type === 'button' || n.type === 'submit') && n.value) n.value = SD_T(n.value);
    for (var c = n.firstChild; c; c = c.nextSibling) el(c);
  }
  var w = window, a0 = w.alert, c0 = w.confirm, p0 = w.prompt;
  w.alert = function (m) { return a0.call(w, SD_T(String(m))); };
  w.confirm = function (m) { return c0.call(w, SD_T(String(m))); };
  w.prompt = function (m, d) { return p0.call(w, SD_T(String(m)), d); };
  function start() {
    if (document.title) document.title = SD_T(document.title);
    el(document.body || document.documentElement);
    new MutationObserver(function (lista) {
      lista.forEach(function (m) {
        if (m.type === 'characterData') el(m.target);
        else if (m.type === 'attributes') el(m.target);
        else m.addedNodes.forEach(el);
      });
    }).observe(document.documentElement, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ATR });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start); else start();
})();
