using System;
using System.Collections.Generic;
using System.Globalization;
using System.Windows;
using System.Windows.Controls;

namespace Przegladarka
{
    // Jezyk interfejsu: polski (oryginal w kodzie) albo angielski (slownik ponizej).
    // L.T("polski tekst") zwraca tlumaczenie, gdy wybrano angielski, a gdy brak wpisu - tekst polski.
    public static class L
    {
        public static bool En { get; private set; }

        // ustawienie: "auto" (jezyk Windows), "pl", "en"
        public static void Init(string setting)
        {
            setting = (setting ?? "auto").Trim().ToLowerInvariant();
            En = setting == "en" || (setting != "pl" && CultureInfo.CurrentUICulture.TwoLetterISOLanguageName != "pl");
        }

        public static string T(string pl)
        {
            string en;
            return En && pl != null && D.TryGetValue(pl, out en) ? en : pl;
        }

        // Tlumaczy napisy okna zbudowanego w XAML: tresc przyciskow, dymki, teksty, pozycje menu.
        public static void TranslateTree(DependencyObject root)
        {
            if (!En || root == null) return;
            if (root is FrameworkElement fe && fe.ToolTip is string tip) fe.ToolTip = T(tip);
            if (root is HeaderedItemsControl hi && hi.Header is string h) hi.Header = T(h);
            if (root is ContentControl cc && cc.Content is string c) cc.Content = T(c);
            if (root is TextBlock tb && !string.IsNullOrEmpty(tb.Text)) tb.Text = T(tb.Text);
            foreach (var child in LogicalTreeHelper.GetChildren(root))
                if (child is DependencyObject d) TranslateTree(d);
        }

        static readonly Dictionary<string, string> D = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // ---- okno glowne (XAML) ----
            { "Czytnik", "Reader" },
            { "Prywatność", "Privacy" },
            { "Prywatność*", "Privacy*" },
            { "➕ Dodaj do Velivo", "➕ Add to Velivo" },
            { "Aktywny profil", "Active profile" },
            { "Czytaj stronę na głos (Ctrl+Shift+U)", "Read page aloud (Ctrl+Shift+U)" },
            { "Dalej (Alt+→)", "Forward (Alt+→)" },
            { "Wstecz (Alt+←)", "Back (Alt+←)" },
            { "Odśwież (F5)", "Reload (F5)" },
            { "Strona startowa", "Home page" },
            { "Dodaj/usuń zakładkę (Ctrl+D)", "Add/remove bookmark (Ctrl+D)" },
            { "Dodatki (tryb dewelopera)", "Extensions (developer mode)" },
            { "Historia (Ctrl+H)", "History (Ctrl+H)" },
            { "Nowa karta (Ctrl+T)", "New tab (Ctrl+T)" },
            { "Nowa karta prywatna (Ctrl+Shift+N) – nic nie zapisuje", "New private tab (Ctrl+Shift+N) – saves nothing" },
            { "Panel prywatności i antyfingerprinting", "Privacy and anti-fingerprinting panel" },
            { "Aktywna reguła prywatności dla tej domeny", "Active privacy rule for this domain" },
            { "Pobiera ten dodatek ze sklepu i instaluje go", "Downloads this extension from the store and installs it" },
            { "Pobrane pliki (Ctrl+J)", "Downloads (Ctrl+J)" },
            { "Prędkość czytania (kliknij, aby zmienić)", "Reading speed (click to change)" },
            { "Tryb ciemny stron", "Dark mode for pages" },
            { "Tryb czytania + lokalne streszczenie", "Reader mode + local summary" },
            { "Ustawienia", "Settings" },
            { "Więcej narzędzi", "More tools" },
            { "Wszystkie zakładki", "All bookmarks" },
            { "Włącz/wyłącz AdBlock", "Turn AdBlock on/off" },
            { "Zatrzymaj czytanie", "Stop reading" },
            { "Zrzut ekranu strony (widoczna część lub cała strona)", "Page screenshot (visible part or full page)" },
            { "Nowa karta", "New tab" },
            { "🕶 Prywatna", "🕶 Private" },
            { "wyłączony", "off" },

            // ---- pasek: menu "wiecej" ----
            { "Tryb czytania", "Reader mode" },
            { "Zrzut ekranu", "Screenshot" },
            { "Czytaj na głos", "Read aloud" },
            { "Tryb ciemny", "Dark mode" },
            { "Pobrane pliki", "Downloads" },
            { "Dodatki", "Extensions" },
            { "Historia", "History" },
            { "Zakładki", "Bookmarks" },

            // ---- menu karty ----
            { "Odśwież", "Reload" },
            { "Duplikuj kartę", "Duplicate tab" },
            { "Zamknij kartę (Ctrl+W)", "Close tab (Ctrl+W)" },
            { "Zamknij inne karty", "Close other tabs" },
            { "Zamknij karty po prawej", "Close tabs to the right" },
            { "Przywróć zamkniętą kartę (Ctrl+Shift+T)", "Reopen closed tab (Ctrl+Shift+T)" },

            // ---- powiekszenie ----
            { "Powiększ (Ctrl +)", "Zoom in (Ctrl +)" },
            { "Pomniejsz (Ctrl −)", "Zoom out (Ctrl −)" },
            { "Domyślne (Ctrl 0)", "Default (Ctrl 0)" },

            // ---- menu pod prawym przyciskiem ----
            { "Przetłumacz zaznaczenie na polski", "Translate selection to Polish" },
            { "Czytaj zaznaczenie na głos", "Read selection aloud" },
            { "Przetłumacz stronę na polski", "Translate page to Polish" },
            { "Przetłumacz stronę na angielski", "Translate page to English" },
            { "🚫 Blokuj element (reklamę)…", "🚫 Block element (ad)…" },
            { "Przywróć zablokowane elementy na tej stronie", "Restore blocked elements on this page" },
            { "Tryb czytania i streszczenie", "Reader mode and summary" },
            { "Czytaj stronę na głos (Ctrl+Shift+U) ", "Read page aloud (Ctrl+Shift+U) " },
            { "Widoczna część strony", "Visible part of the page" },
            { "Cała strona (z przewijaniem)", "Full page (scrolling)" },
            { "Narzędzia Velivo", "Velivo tools" },
            { "Prywatność i antyfingerprinting", "Privacy and anti-fingerprinting" },
            { "Wykryj media do pobrania", "Detect downloadable media" },
            { "Menedżer pobrań", "Download manager" },
            { "Diagnostyka LAN sync", "LAN sync diagnostics" },
            { "Przełącz profil: praca", "Switch profile: work" },
            { "Przełącz użytkownika/profil…", "Switch user/profile…" },

            // ---- tryb ciemny / nocny ----
            { "Tryb ciemny stron: WŁĄCZONY\nKliknij, aby wyłączyć", "Dark mode for pages: ON\nClick to turn off" },
            { "Tryb ciemny stron: wyłączony\nKliknij, aby przyciemnić strony (zdjęcia zostają w prawdziwych kolorach)", "Dark mode for pages: off\nClick to darken pages (photos keep their real colors)" },
            { "Tryb nocny: WŁĄCZONY (cieplejsze kolory)\nKliknij, aby wrócić do trybu jasnego", "Night mode: ON (warmer colors)\nClick to return to light mode" },
            { "🌙 Tryb ciemny", "🌙 Dark mode" },
            { "🌅 Tryb nocny – cieplejsze kolory", "🌅 Night mode – warmer colors" },
            { "☀ Tryb jasny", "☀ Light mode" },

            // ---- etap 2: ustawienia, prywatnosc, profile ----
            { "Domyślna przeglądarka", "Default browser" },
            { "✓ Velivo jest domyślną przeglądarką.", "✓ Velivo is the default browser." },
            { "Velivo nie jest teraz domyślną przeglądarką.", "Velivo is not the default browser right now." },
            { "Ustaw Velivo jako domyślną przeglądarkę…", "Set Velivo as the default browser…" },
            { "Wygląd i czytelność", "Appearance and readability" },
            { "Domyślne powiększenie stron (każdą stronę możesz też powiększyć osobno: Ctrl + kółko myszy):", "Default page zoom (you can also zoom each page separately: Ctrl + mouse wheel):" },
            { "Tryb ciemny stron (przycisk z księżycem na pasku)", "Dark mode for pages (moon button on the toolbar)" },
            { "Strony z własnym ciemnym wyglądem przełączają się na niego, pozostałe jasne strony są przyciemniane.", "Pages with their own dark look switch to it; other light pages are darkened." },
            { "Tryb nocny – cieplejsze kolory stron (jak Światło nocne w Windows)", "Night mode – warmer page colors (like Windows Night light)" },
            { "Mniej niebieskiego światła wieczorem. Przycisk z księżycem przełącza: jasny → ciemny → nocny.", "Less blue light in the evening. The moon button cycles: light → dark → night." },
            { "Motyw przeglądarki (kolory pasków i kart):", "Browser theme (toolbar and tab colors):" },
            { "Zawsze kompaktowy pasek narzędzi", "Always compact toolbar" },
            { "Zmniejsza etykiety i przenosi część przycisków do menu „…”, nawet na szerokim oknie.", "Shrinks labels and moves some buttons to the “…” menu, even in a wide window." },
            { "Czytanie na głos – głos i prędkość:", "Read aloud – voice and speed:" },
            { "Automatycznie (język strony: polski/angielski)", "Automatic (page language: Polish/English)" },
            { " (angielski", " (English" },
            { " (polski", " (Polish" },
            { ", online – naturalny)", ", online – natural)" },
            { " – pobierze ok. 60 MB", " – downloads approx. 60 MB" },
            { "Po uruchomieniu przywracaj karty z poprzedniej sesji", "Restore tabs from the previous session on startup" },
            { "Karty prywatne nigdy nie są zapisywane. Zamkniętą kartę przywrócisz też skrótem Ctrl+Shift+T.", "Private tabs are never saved. You can also reopen a closed tab with Ctrl+Shift+T." },
            { "Wyszukiwanie i start", "Search and startup" },
            { "Wyszukiwarka w pasku adresu:", "Search engine in the address bar:" },
            { "Strona startowa:", "Home page:" },
            { "Szybki Dostęp jako strona nowej karty", "Quick Access as the new tab page" },
            { "Używa osobnych danych Velivo w folderze danych przeglądarki; Szybki Dostęp Sejfu w innych przeglądarkach pozostaje osobny.", "Uses separate Velivo data in the browser data folder; Sejf's Quick Access in other browsers stays separate." },
            { "Folder rozszerzenia do ręcznej instalacji w innych przeglądarkach:", "Extension folder for manual installation in other browsers:" },
            { "Wybierz ścieżkę i skopiuj ją do okna ładowania rozpakowanego rozszerzenia.", "Select the path and copy it into the “Load unpacked extension” window." },
            { "Wysyłaj sygnały „Nie śledź” (DNT i Global Privacy Control)", "Send “Do Not Track” signals (DNT and Global Privacy Control)" },
            { "Strony dostają prośbę o niesprzedawanie i nieśledzenie Twoich danych.", "Websites are asked not to sell or track your data." },
            { "Ścisła ochrona przed śledzeniem", "Strict tracking prevention" },
            { "Blokuje trackery i ciasteczka śledzące między stronami. Rzadko może psuć niektóre strony.", "Blocks trackers and cross-site tracking cookies. Rarely may break some pages." },
            { "Zapisuj historię przeglądania", "Save browsing history" },
            { "Czyść dane przy zamknięciu (historia i pamięć podręczna)", "Clear data on exit (history and cache)" },
            { "Czyści historię i cache przy zamknięciu, ale nie wylogowuje kont ani nie usuwa zapisanych logowań.", "Clears history and cache on exit, but does not sign you out or delete saved logins." },
            { "Loginy z Sejfu: kluczyk na pasku na stronach logowania", "Sejf logins: key on the toolbar on login pages" },
            { " (nie znaleziono Sejfu)", " (Sejf not found)" },
            { "Gdy strona ma pole hasła, Velivo pyta Sejf o loginy dla tej strony. Kliknięcie kluczyka wypełnia formularz.", "When a page has a password field, Velivo asks Sejf for logins for that page. Clicking the key fills in the form." },
            { "Proponuj zapisywanie haseł", "Offer to save passwords" },
            { "Autouzupełnianie formularzy (adresy i karty, lokalna szyfrowana baza)", "Form autofill (addresses and cards, local encrypted database)" },
            { "Dane formularzy i kart są zapisywane lokalnie w szyfrowanej bazie offline. Hasła dalej obsługuje Sejf.", "Form and card data is stored locally in an encrypted offline database. Passwords are still handled by Sejf." },
            { "Blokuj wyskakujące okna otwierane bez kliknięcia", "Block pop-ups opened without a click" },
            { "Pokaż zapisane dane…", "Show saved data…" },
            { "Usuń zapisane karty", "Delete saved cards" },
            { "Usuń zapisane adresy", "Delete saved addresses" },
            { "Menedżer haseł lokalnych…", "Local password manager…" },
            { "Import haseł CSV…", "Import passwords (CSV)…" },
            { "Eksport haseł CSV…", "Export passwords (CSV)…" },
            { "Blokowanie reklam", "Ad blocking" },
            { "Pełne listy filtrów (EasyList, EasyPrivacy, polska lista) – ok. 97 tys. reguł", "Full filter lists (EasyList, EasyPrivacy, Polish list) – approx. 97k rules" },
            { "Listy pobierają się w tle i odświeżają co 4 dni.", "Lists download in the background and refresh every 4 days." },
            { "Listy: ", "Lists: " },
            { ". Reguł w użyciu: ", ". Rules in use: " },
            { "Aktualizuj listy teraz", "Update lists now" },
            { "Pobieram listy…", "Downloading lists…" },
            { "Pobrano ", "Downloaded " },
            { " z 3 list. Reguł w użyciu: ", " of 3 lists. Rules in use: " },
            { "Bezpieczeństwo i pobieranie", "Security and downloads" },
            { "Ostrzegaj przed niebezpiecznymi stronami i plikami (SmartScreen)", "Warn about dangerous sites and files (SmartScreen)" },
            { "Sprawdzanie adresów wysyła je do Microsoft. Zalecane – chroni przed wyłudzeniami.", "Checking addresses sends them to Microsoft. Recommended – protects against phishing." },
            { "Pytaj, gdzie zapisać każdy pobierany plik", "Ask where to save each download" },
            { "Połączeń na jeden pobierany plik (więcej = zwykle szybciej):", "Connections per download (more = usually faster):" },
            { "1 (bez dzielenia)", "1 (no splitting)" },
            { "Śmieci przeglądarki (pamięć podręczna)", "Browser junk (cache)" },
            { "Cache stron, skompilowane skrypty i cache grafiki. Można je usuwać bez utraty logowań i danych dodatków.", "Page cache, compiled scripts and graphics cache. Can be deleted without losing logins or extension data." },
            { "Folder na śmieci (puste = w profilu przeglądarki):", "Junk folder (empty = in the browser profile):" },
            { "Wybierz…", "Choose…" },
            { "Folder na śmieci przeglądarki", "Browser junk folder" },
            { "Domyślny", "Default" },
            { "Program tworzy w nim podfolder „", "The program creates a subfolder “" },
            { "” i usuwa tylko jego zawartość. Cache grafiki zostaje w profilu (wymóg silnika).", "” in it and deletes only its contents. The graphics cache stays in the profile (engine requirement)." },
            { "Usuwaj śmieci przy każdym uruchomieniu przeglądarki", "Delete junk every time the browser starts" },
            { "Strony wczytają się za pierwszym razem odrobinę wolniej.", "Pages will load slightly slower the first time." },
            { "Teraz zajmują: ", "Currently using: " },
            { "Wyczyść śmieci teraz", "Clear junk now" },
            { "Zwolniono ", "Freed " },
            { ". Teraz zajmują: ", ". Currently using: " },
            { " (cache grafiki zniknie przy następnym uruchomieniu).", " (the graphics cache will disappear on next start)." },
            { "Dane", "Data" },
            { "Wyczyść dane przeglądania teraz…", "Clear browsing data now…" },
            { "Wyczyść dane przeglądania", "Clear browsing data" },
            { "Wybierz, co usunąć:", "Choose what to delete:" },
            { "Historia przeglądania", "Browsing history" },
            { "Pamięć podręczna (cache)", "Cache" },
            { "Historia pobrań", "Download history" },
            { "Cookies i aktywne sesje (wyloguje konta)", "Cookies and active sessions (signs you out)" },
            { "Dane formularzy i kart zapisane przez silnik", "Form and card data saved by the engine" },
            { "Zapisane hasła w silniku", "Passwords saved in the engine" },
            { "Uwaga: usunięcie cookies/sesji spowoduje wylogowanie ze stron.", "Note: deleting cookies/sessions will sign you out of websites." },
            { "Wyczyść", "Clear" },
            { "Anuluj", "Cancel" },
            { "Nie zaznaczono żadnych danych do usunięcia.", "No data selected for deletion." },
            { "Wyczyszczono zaznaczone dane.", "Selected data cleared." },
            { "Prywatność per-strona", "Per-site privacy" },
            { "Panel prywatności i antyfingerprinting…", "Privacy and anti-fingerprinting panel…" },
            { "Profile użytkownika", "User profiles" },
            { "Aktywny profil: ", "Active profile: " },
            { "Praca", "Work" },
            { "Prywatny", "Private" },
            { "Zarządzaj użytkownikami/profilami…", "Manage users/profiles…" },
            { "Synchronizacja E2E", "E2E sync" },
            { "Lokalny eksport/import zaszyfrowanej paczki (hasło + AES-GCM). Możesz przenieść plik na inne urządzenie.", "Local export/import of an encrypted package (password + AES-GCM). You can move the file to another device." },
            { "Eksportuj paczkę…", "Export package…" },
            { "Importuj paczkę…", "Import package…" },
            { "Synchronizacja w czasie rzeczywistym (LAN):", "Real-time sync (LAN):" },
            { "Włącz synchronizację między uruchomionymi Velivo w tej samej sieci lokalnej", "Enable sync between running Velivo instances on the same local network" },
            { "Synchronizuje ustawienia, zakładki, hasła, reguły prywatności i Szybki Dostęp dla tego samego profilu. Otwarte karty zostają na każdym komputerze osobno.", "Syncs settings, bookmarks, passwords, privacy rules and Quick Access for the same profile. Open tabs stay separate on each computer." },
            { "Włącz i zapisz synchronizację na obu komputerach. Sparuj je jednorazowo, porównując krótki kod; sekret zostanie zapisany lokalnie.", "Enable and save sync on both computers. Pair them once by comparing a short code; the secret is stored locally." },
            { "Sparuj urządzenie w sieci…", "Pair a device on the network…" },
            { "Zapisz plik odzyskiwania…", "Save recovery file…" },
            { "Odtwórz parowanie…", "Restore pairing…" },
            { "Tryb cichy LAN (bez dymków „Zsynchronizowano profil…”)", "Quiet LAN mode (no “Profile synced…” pop-ups)" },
            { "Log i panel diagnostyczny nadal działają, wyłączone są tylko wyskakujące komunikaty.", "The log and diagnostics panel still work; only pop-up messages are turned off." },
            { "Panel diagnostyczny LAN…", "LAN diagnostics panel…" },
            { "Zapisz", "Save" },
            { "Nie można używać tego folderu na śmieci:\n", "This junk folder cannot be used:\n" },
            { "Nie zapisano ustawień:\n", "Settings were not saved:\n" },
            { "Nowy folder na śmieci zacznie działać po ponownym uruchomieniu przeglądarki.", "The new junk folder will take effect after restarting the browser." },
            { "\nKliknij, aby przełączyć użytkownika/profil", "\nClick to switch user/profile" },
            { "Skrypt (JS) zablokowany regułą domeny", "Script (JS) blocked by domain rule" },
            { "Tracker zablokowany (reguła domeny)", "Tracker blocked (domain rule)" },
            { "Tracker zablokowany (AdBlock)", "Tracker blocked (AdBlock)" },
            { "Automatyczne czyszczenie danych domeny", "Automatic domain data clearing" },
            { "Cookies usunięte dla domeny (reguła)", "Cookies deleted for domain (rule)" },
            { "Godzina", "Time" },
            { "Domena", "Domain" },
            { "Powód", "Reason" },
            { "Tryb", "Mode" },
            { "Domena:", "Domain:" },
            { "Blokuj JavaScript dla domeny", "Block JavaScript for this domain" },
            { "Nie wysyłaj cookies dla domeny", "Don't send cookies for this domain" },
            { "Wymuś blokowanie trackerów dla domeny", "Force tracker blocking for this domain" },
            { "Automatycznie czyść dane po wejściu na domenę", "Automatically clear data when visiting this domain" },
            { "Zaufana domena (bez blokowania i SmartScreen)", "Trusted domain (no blocking and no SmartScreen)" },
            { "Reguły działają per domena. Karty prywatne używają osobnego, izolowanego storage WebView2 (InPrivate).", "Rules apply per domain. Private tabs use separate, isolated WebView2 storage (InPrivate)." },
            { "Prywat.", "Private" },
            { "Zwykły", "Normal" },
            { "Szybki Dostęp to wbudowany dodatek – jest zaufany na stałe i nic go nie blokuje. Nie trzeba dodawać reguły.", "Quick Access is a built-in extension – it is permanently trusted and nothing blocks it. No rule is needed." },
            { "Godzina: ", "Time: " },
            { "\nDomena: ", "\nDomain: " },
            { "\nPowód: ", "\nReason: " },
            { "\nTryb: ", "\nMode: " },
            { "Zapisz regułę", "Save rule" },
            { "Podaj poprawną domenę stron www, np. example.com (adresy chrome-extension:// dodatków nie są blokowane regułami).", "Enter a valid website domain, e.g. example.com (chrome-extension:// addresses are not blocked by rules)." },
            { "Domena: ", "Domain: " },
            { "Zapisać mimo to?", "Save anyway?" },
            { "Usuń regułę", "Delete rule" },
            { "Podaj poprawną domenę stron www, np. example.com", "Enter a valid website domain, e.g. example.com" },
            { "Zaufane domeny", "Trusted domains" },
            { "✔ Dodaj do zaufanych", "✔ Add to trusted" },
            { "✔ Zaznaczoną domenę do zaufanych", "✔ Trust selected domain" },
            { "Najpierw zaznacz wpis na liście blokad.", "First select an entry in the block list." },
            { "Wyczyść panel blokad", "Clear block list" },
            { "Więcej…", "More…" },
            { "Reguły prywatności dla domen", "Privacy rules for domains" },
            { "Zapisane reguły domen", "Saved domain rules" },
            { "Co zostało zablokowane i dlaczego", "What was blocked and why" },
            { "Wybierz wpis, aby zobaczyć pełny URL i szczegóły blokady.", "Select an entry to see the full URL and block details." },
            { "Szczegóły zaznaczonego wpisu", "Details of the selected entry" },
            { "Przełączyć profil na „", "Switch profile to “" },
            { "”?\nAplikacja uruchomi się ponownie z osobnym zestawem kart, historii i dodatków.", "”?\nThe app will restart with a separate set of tabs, history and extensions." },
            { "Profil", "Profile" },
            { "Użytkownicy i profile Velivo", "Velivo users and profiles" },
            { "Ikona profilu:", "Profile icon:" },
            { "Zapisz ikonkę", "Save icon" },
            { " (aktywny)", " (active)" },
            { "Dodaj użytkownika/profil…", "Add user/profile…" },
            { "Nazwa użytkownika/profilu (np. google-konto2):", "User/profile name (e.g. google-account2):" },
            { "Niepoprawna nazwa.", "Invalid name." },
            { "Profile", "Profiles" },
            { "Przełącz na zaznaczony", "Switch to selected" },
            { "Usuń zaznaczony profil", "Delete selected profile" },
            { "Nie można usunąć aktywnego ani domyślnego profilu.", "The active or default profile cannot be deleted." },
            { "Usunąć profil „", "Delete profile “" },
            { "” razem z jego lokalnymi danymi?", "” together with its local data?" },
            { "Każdy profil ma własne ustawienia, sesje, historię, zakładki i dodatki. Sejf oraz Szybki Dostęp pozostają wspólne i nie są tutaj zmieniane.", "Each profile has its own settings, sessions, history, bookmarks and extensions. Sejf and Quick Access stay shared and are not changed here." },
            { "Ta reguła może powodować utratę logowania i ustawień strony (cookies/sesja/localStorage).\n\n", "This rule may cause loss of logins and site settings (cookies/session/localStorage).\n\n" },
            { "Jasny (domyślny)", "Light (default)" },
            { "Grafit", "Graphite" },
            { "Granat", "Navy" },
            { "Nocny fiolet", "Night violet" },
            { "Las", "Forest" },
            { "Zachód słońca", "Sunset" },
            { "Czerń (OLED)", "Black (OLED)" },
            { "Papier", "Paper" },
            { "Mgła", "Mist" },
            { "Gosia (polski, naturalny offline)", "Gosia (Polish, natural offline)" },
            { "Darkman (polski, naturalny offline)", "Darkman (Polish, natural offline)" },
            { "MC Speech (polski, naturalny offline)", "MC Speech (Polish, natural offline)" },
            { "Lessac (angielski US, naturalny offline)", "Lessac (English US, natural offline)" },
            { "Ryan (angielski US, naturalny offline)", "Ryan (English US, natural offline)" },
            { "Alba (angielski UK, naturalny offline)", "Alba (English UK, natural offline)" },

            // ---- ustawienia: jezyk ----
            { "Język interfejsu / Language:", "Language / Język interfejsu:" },
            { "Automatycznie (język Windows)", "Automatic (Windows language)" },
            { "Zmiana języka zadziała po ponownym uruchomieniu Velivo.", "The language change takes effect after restarting Velivo." },
        };
    }
}
