using System;
using System.Collections.Generic;
using System.Globalization;
using System.Windows;
using System.Windows.Controls;

namespace Przegladarka
{
    // Jezyk interfejsu: polski (oryginal w kodzie) albo angielski (slownik ponizej).
    // L.T("polski tekst") zwraca tlumaczenie, gdy wybrano angielski, a gdy brak wpisu - tekst polski.
    public static class L
    {
        public static bool En { get; private set; }

        // ustawienie: "auto" (jezyk Windows), "pl", "en"
        public static void Init(string setting)
        {
            setting = (setting ?? "auto").Trim().ToLowerInvariant();
            // "automatycznie": najpierw jezyk wybrany w instalatorze (language.txt obok programu), potem jezyk Windows
            if (setting == "auto")
            {
                try
                {
                    var f = System.IO.Path.Combine(AppContext.BaseDirectory, "language.txt");
                    if (System.IO.File.Exists(f))
                    {
                        var v = System.IO.File.ReadAllText(f).Trim().ToLowerInvariant();
                        if (v == "pl" || v == "en") setting = v;
                    }
                }
                catch (Exception) { }
            }
            En = setting == "en" || (setting != "pl" && CultureInfo.CurrentUICulture.TwoLetterISOLanguageName != "pl");
        }

        public static string T(string pl)
        {
            string en;
            return En && pl != null && D.TryGetValue(pl, out en) ? en : pl;
        }

        // Tlumaczy napisy okna zbudowanego w XAML: tresc przyciskow, dymki, teksty, pozycje menu.
        public static void TranslateTree(DependencyObject root)
        {
            if (!En || root == null) return;
            if (root is FrameworkElement fe && fe.ToolTip is string tip) fe.ToolTip = T(tip);
            if (root is HeaderedItemsControl hi && hi.Header is string h) hi.Header = T(h);
            if (root is ContentControl cc && cc.Content is string c) cc.Content = T(c);
            if (root is TextBlock tb && !string.IsNullOrEmpty(tb.Text)) tb.Text = T(tb.Text);
            foreach (var child in LogicalTreeHelper.GetChildren(root))
                if (child is DependencyObject d) TranslateTree(d);
        }

        static readonly Dictionary<string, string> D = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // ---- okno glowne (XAML) ----
            { "Czytnik", "Reader" },
            { "Prywatność", "Privacy" },
            { "Prywatność*", "Privacy*" },
            { "➕ Dodaj do Velivo", "➕ Add to Velivo" },
            { "Aktywny profil", "Active profile" },
            { "Czytaj stronę na głos (Ctrl+Shift+U)", "Read page aloud (Ctrl+Shift+U)" },
            { "Dalej (Alt+→)", "Forward (Alt+→)" },
            { "Wstecz (Alt+←)", "Back (Alt+←)" },
            { "Odśwież (F5)", "Reload (F5)" },
            { "Strona startowa", "Home page" },
            { "Dodaj/usuń zakładkę (Ctrl+D)", "Add/remove bookmark (Ctrl+D)" },
            { "Dodatki (tryb dewelopera)", "Extensions (developer mode)" },
            { "Historia (Ctrl+H)", "History (Ctrl+H)" },
            { "Nowa karta (Ctrl+T)", "New tab (Ctrl+T)" },
            { "Nowa karta prywatna (Ctrl+Shift+N) – nic nie zapisuje", "New private tab (Ctrl+Shift+N) – saves nothing" },
            { "Panel prywatności i antyfingerprinting", "Privacy and anti-fingerprinting panel" },
            { "Aktywna reguła prywatności dla tej domeny", "Active privacy rule for this domain" },
            { "Pobiera ten dodatek ze sklepu i instaluje go", "Downloads this extension from the store and installs it" },
            { "Pobrane pliki (Ctrl+J)", "Downloads (Ctrl+J)" },
            { "Prędkość czytania (kliknij, aby zmienić)", "Reading speed (click to change)" },
            { "Tryb ciemny stron", "Dark mode for pages" },
            { "Tryb czytania + lokalne streszczenie", "Reader mode + local summary" },
            { "Ustawienia", "Settings" },
            { "Więcej narzędzi", "More tools" },
            { "Wszystkie zakładki", "All bookmarks" },
            { "Włącz/wyłącz AdBlock", "Turn AdBlock on/off" },
            { "Zatrzymaj czytanie", "Stop reading" },
            { "Zrzut ekranu strony (widoczna część lub cała strona)", "Page screenshot (visible part or full page)" },
            { "Nowa karta", "New tab" },
            { "🕶 Prywatna", "🕶 Private" },
            { "wyłączony", "off" },
            { "Zablokowane na tej stronie", "Blocked on this page" },
            { "Elementy", "Elements" },
            { " ukrytych elementów (reguły ręczne)", " hidden elements (manual rules)" },
            { "Nic nie zablokowano na tej stronie.", "Nothing blocked on this page." },
            { "Wyłącz AdBlock", "Turn AdBlock off" },
            { "Włącz AdBlock", "Turn AdBlock on" },
            { "Reguła domeny", "Domain rule" },
            { "Zablokowane elementy", "Blocked items" },

            // ---- pasek: menu "wiecej" ----
            { "Tryb czytania", "Reader mode" },
            { "Zrzut ekranu", "Screenshot" },
            { "Czytaj na głos", "Read aloud" },
            { "Tryb ciemny", "Dark mode" },
            { "Pobrane pliki", "Downloads" },
            { "Dodatki", "Extensions" },
            { "Historia", "History" },
            { "Zakładki", "Bookmarks" },

            // ---- menu karty ----
            { "Odśwież", "Reload" },
            { "Duplikuj kartę", "Duplicate tab" },
            { "Zamknij kartę (Ctrl+W)", "Close tab (Ctrl+W)" },
            { "Zamknij inne karty", "Close other tabs" },
            { "Zamknij karty po prawej", "Close tabs to the right" },
            { "Przywróć zamkniętą kartę (Ctrl+Shift+T)", "Reopen closed tab (Ctrl+Shift+T)" },

            // ---- powiekszenie ----
            { "Powiększ (Ctrl +)", "Zoom in (Ctrl +)" },
            { "Pomniejsz (Ctrl −)", "Zoom out (Ctrl −)" },
            { "Domyślne (Ctrl 0)", "Default (Ctrl 0)" },

            // ---- menu pod prawym przyciskiem ----
            { "Przetłumacz zaznaczenie na polski", "Translate selection to Polish" },
            { "Czytaj zaznaczenie na głos", "Read selection aloud" },
            { "Przetłumacz stronę na polski", "Translate page to Polish" },
            { "Przetłumacz stronę na angielski", "Translate page to English" },
            { "🚫 Blokuj element (reklamę)…", "🚫 Block element (ad)…" },
            { "Przywróć zablokowane elementy na tej stronie", "Restore blocked elements on this page" },
            { "Tryb czytania i streszczenie", "Reader mode and summary" },
            { "Czytaj stronę na głos (Ctrl+Shift+U) ", "Read page aloud (Ctrl+Shift+U) " },
            { "Widoczna część strony", "Visible part of the page" },
            { "Cała strona (z przewijaniem)", "Full page (scrolling)" },
            { "Narzędzia Velivo", "Velivo tools" },
            { "Prywatność i antyfingerprinting", "Privacy and anti-fingerprinting" },
            { "Wykryj media do pobrania", "Detect downloadable media" },
            { "Menedżer pobrań", "Download manager" },
            { "Diagnostyka LAN sync", "LAN sync diagnostics" },
            { "Przełącz profil: praca", "Switch profile: work" },
            { "Przełącz użytkownika/profil…", "Switch user/profile…" },

            // ---- tryb ciemny / nocny ----
            { "Tryb ciemny stron: WŁĄCZONY\nKliknij, aby wyłączyć", "Dark mode for pages: ON\nClick to turn off" },
            { "Tryb ciemny stron: wyłączony\nKliknij, aby przyciemnić strony (zdjęcia zostają w prawdziwych kolorach)", "Dark mode for pages: off\nClick to darken pages (photos keep their real colors)" },
            { "Tryb nocny: WŁĄCZONY (cieplejsze kolory)\nKliknij, aby wrócić do trybu jasnego", "Night mode: ON (warmer colors)\nClick to return to light mode" },
            { "🌙 Tryb ciemny", "🌙 Dark mode" },
            { "🌅 Tryb nocny – cieplejsze kolory", "🌅 Night mode – warmer colors" },
            { "☀ Tryb jasny", "☀ Light mode" },

            // ---- etap 2: ustawienia, prywatnosc, profile ----
            { "Domyślna przeglądarka", "Default browser" },
            { "✓ Velivo jest domyślną przeglądarką.", "✓ Velivo is the default browser." },
            { "Velivo nie jest teraz domyślną przeglądarką.", "Velivo is not the default browser right now." },
            { "Ustaw Velivo jako domyślną przeglądarkę…", "Set Velivo as the default browser…" },
            { "Wygląd i czytelność", "Appearance and readability" },
            { "Domyślne powiększenie stron (każdą stronę możesz też powiększyć osobno: Ctrl + kółko myszy):", "Default page zoom (you can also zoom each page separately: Ctrl + mouse wheel):" },
            { "Tryb ciemny stron (przycisk z księżycem na pasku)", "Dark mode for pages (moon button on the toolbar)" },
            { "Strony z własnym ciemnym wyglądem przełączają się na niego, pozostałe jasne strony są przyciemniane.", "Pages with their own dark look switch to it; other light pages are darkened." },
            { "Tryb nocny – cieplejsze kolory stron (jak Światło nocne w Windows)", "Night mode – warmer page colors (like Windows Night light)" },
            { "Mniej niebieskiego światła wieczorem. Przycisk z księżycem przełącza: jasny → ciemny → nocny.", "Less blue light in the evening. The moon button cycles: light → dark → night." },
            { "Motyw przeglądarki (kolory pasków i kart):", "Browser theme (toolbar and tab colors):" },
            { "Zawsze kompaktowy pasek narzędzi", "Always compact toolbar" },
            { "Zmniejsza etykiety i przenosi część przycisków do menu „…”, nawet na szerokim oknie.", "Shrinks labels and moves some buttons to the “…” menu, even in a wide window." },
            { "Czytanie na głos – głos i prędkość:", "Read aloud – voice and speed:" },
            { "Automatycznie (język strony: polski/angielski)", "Automatic (page language: Polish/English)" },
            { " (angielski", " (English" },
            { " (polski", " (Polish" },
            { ", online – naturalny)", ", online – natural)" },
            { " – pobierze ok. 60 MB", " – downloads approx. 60 MB" },
            { "Po uruchomieniu przywracaj karty z poprzedniej sesji", "Restore tabs from the previous session on startup" },
            { "Karty prywatne nigdy nie są zapisywane. Zamkniętą kartę przywrócisz też skrótem Ctrl+Shift+T.", "Private tabs are never saved. You can also reopen a closed tab with Ctrl+Shift+T." },
            { "Wyszukiwanie i start", "Search and startup" },
            { "Wyszukiwarka w pasku adresu:", "Search engine in the address bar:" },
            { "Strona startowa:", "Home page:" },
            { "Szybki Dostęp jako strona nowej karty", "Quick Access as the new tab page" },
            { "Używa osobnych danych Velivo w folderze danych przeglądarki; Szybki Dostęp Sejfu w innych przeglądarkach pozostaje osobny.", "Uses separate Velivo data in the browser data folder; Sejf's Quick Access in other browsers stays separate." },
            { "Folder rozszerzenia do ręcznej instalacji w innych przeglądarkach:", "Extension folder for manual installation in other browsers:" },
            { "Wybierz ścieżkę i skopiuj ją do okna ładowania rozpakowanego rozszerzenia.", "Select the path and copy it into the “Load unpacked extension” window." },
            { "Wysyłaj sygnały „Nie śledź” (DNT i Global Privacy Control)", "Send “Do Not Track” signals (DNT and Global Privacy Control)" },
            { "Strony dostają prośbę o niesprzedawanie i nieśledzenie Twoich danych.", "Websites are asked not to sell or track your data." },
            { "Ścisła ochrona przed śledzeniem", "Strict tracking prevention" },
            { "Blokuje trackery i ciasteczka śledzące między stronami. Rzadko może psuć niektóre strony.", "Blocks trackers and cross-site tracking cookies. Rarely may break some pages." },
            { "Zapisuj historię przeglądania", "Save browsing history" },
            { "Czyść dane przy zamknięciu (historia i pamięć podręczna)", "Clear data on exit (history and cache)" },
            { "Czyści historię i cache przy zamknięciu, ale nie wylogowuje kont ani nie usuwa zapisanych logowań.", "Clears history and cache on exit, but does not sign you out or delete saved logins." },
            { "Loginy z Sejfu: kluczyk na pasku na stronach logowania", "Sejf logins: key on the toolbar on login pages" },
            { " (nie znaleziono Sejfu)", " (Sejf not found)" },
            { "Gdy strona ma pole hasła, Velivo pyta Sejf o loginy dla tej strony. Kliknięcie kluczyka wypełnia formularz.", "When a page has a password field, Velivo asks Sejf for logins for that page. Clicking the key fills in the form." },
            { "Proponuj zapisywanie haseł", "Offer to save passwords" },
            { "Autouzupełnianie formularzy (adresy i karty, lokalna szyfrowana baza)", "Form autofill (addresses and cards, local encrypted database)" },
            { "Dane formularzy i kart są zapisywane lokalnie w szyfrowanej bazie offline. Hasła dalej obsługuje Sejf.", "Form and card data is stored locally in an encrypted offline database. Passwords are still handled by Sejf." },
            { "Blokuj wyskakujące okna otwierane bez kliknięcia", "Block pop-ups opened without a click" },
            { "Pokaż zapisane dane…", "Show saved data…" },
            { "Usuń zapisane karty", "Delete saved cards" },
            { "Usuń zapisane adresy", "Delete saved addresses" },
            { "Menedżer haseł lokalnych…", "Local password manager…" },
            { "Import haseł CSV…", "Import passwords (CSV)…" },
            { "Eksport haseł CSV…", "Export passwords (CSV)…" },
            { "Blokowanie reklam", "Ad blocking" },
            { "Pełne listy filtrów (EasyList, EasyPrivacy, polska lista) – ok. 97 tys. reguł", "Full filter lists (EasyList, EasyPrivacy, Polish list) – approx. 97k rules" },
            { "Listy pobierają się w tle i odświeżają co 4 dni.", "Lists download in the background and refresh every 4 days." },
            { "Listy: ", "Lists: " },
            { ". Reguł w użyciu: ", ". Rules in use: " },
            { "Aktualizuj listy teraz", "Update lists now" },
            { "Pobieram listy…", "Downloading lists…" },
            { "Pobrano ", "Downloaded " },
            { " z 3 list. Reguł w użyciu: ", " of 3 lists. Rules in use: " },
            { "Bezpieczeństwo i pobieranie", "Security and downloads" },
            { "Ostrzegaj przed niebezpiecznymi stronami i plikami (SmartScreen)", "Warn about dangerous sites and files (SmartScreen)" },
            { "Sprawdzanie adresów wysyła je do Microsoft. Zalecane – chroni przed wyłudzeniami.", "Checking addresses sends them to Microsoft. Recommended – protects against phishing." },
            { "Pytaj, gdzie zapisać każdy pobierany plik", "Ask where to save each download" },
            { "Połączeń na jeden pobierany plik (więcej = zwykle szybciej):", "Connections per download (more = usually faster):" },
            { "1 (bez dzielenia)", "1 (no splitting)" },
            { "Śmieci przeglądarki (pamięć podręczna)", "Browser junk (cache)" },
            { "Cache stron, skompilowane skrypty i cache grafiki. Można je usuwać bez utraty logowań i danych dodatków.", "Page cache, compiled scripts and graphics cache. Can be deleted without losing logins or extension data." },
            { "Folder na śmieci (puste = w profilu przeglądarki):", "Junk folder (empty = in the browser profile):" },
            { "Wybierz…", "Choose…" },
            { "Folder na śmieci przeglądarki", "Browser junk folder" },
            { "Domyślny", "Default" },
            { "Program tworzy w nim podfolder „", "The program creates a subfolder “" },
            { "” i usuwa tylko jego zawartość. Cache grafiki zostaje w profilu (wymóg silnika).", "” in it and deletes only its contents. The graphics cache stays in the profile (engine requirement)." },
            { "Usuwaj śmieci przy każdym uruchomieniu przeglądarki", "Delete junk every time the browser starts" },
            { "Strony wczytają się za pierwszym razem odrobinę wolniej.", "Pages will load slightly slower the first time." },
            { "Teraz zajmują: ", "Currently using: " },
            { "Wyczyść śmieci teraz", "Clear junk now" },
            { "Zwolniono ", "Freed " },
            { ". Teraz zajmują: ", ". Currently using: " },
            { " (cache grafiki zniknie przy następnym uruchomieniu).", " (the graphics cache will disappear on next start)." },
            { "Dane", "Data" },
            { "Wyczyść dane przeglądania teraz…", "Clear browsing data now…" },
            { "Wyczyść dane przeglądania", "Clear browsing data" },
            { "Wybierz, co usunąć:", "Choose what to delete:" },
            { "Historia przeglądania", "Browsing history" },
            { "Pamięć podręczna (cache)", "Cache" },
            { "Historia pobrań", "Download history" },
            { "Cookies i aktywne sesje (wyloguje konta)", "Cookies and active sessions (signs you out)" },
            { "Dane formularzy i kart zapisane przez silnik", "Form and card data saved by the engine" },
            { "Zapisane hasła w silniku", "Passwords saved in the engine" },
            { "Uwaga: usunięcie cookies/sesji spowoduje wylogowanie ze stron.", "Note: deleting cookies/sessions will sign you out of websites." },
            { "Wyczyść", "Clear" },
            { "Anuluj", "Cancel" },
            { "Nie zaznaczono żadnych danych do usunięcia.", "No data selected for deletion." },
            { "Wyczyszczono zaznaczone dane.", "Selected data cleared." },
            { "Prywatność per-strona", "Per-site privacy" },
            { "Panel prywatności i antyfingerprinting…", "Privacy and anti-fingerprinting panel…" },
            { "Profile użytkownika", "User profiles" },
            { "Aktywny profil: ", "Active profile: " },
            { "Praca", "Work" },
            { "Prywatny", "Private" },
            { "Zarządzaj użytkownikami/profilami…", "Manage users/profiles…" },
            { "Synchronizacja E2E", "E2E sync" },
            { "Lokalny eksport/import zaszyfrowanej paczki (hasło + AES-GCM). Możesz przenieść plik na inne urządzenie.", "Local export/import of an encrypted package (password + AES-GCM). You can move the file to another device." },
            { "Eksportuj paczkę…", "Export package…" },
            { "Importuj paczkę…", "Import package…" },
            { "Synchronizacja w czasie rzeczywistym (LAN):", "Real-time sync (LAN):" },
            { "Włącz synchronizację między uruchomionymi Velivo w tej samej sieci lokalnej", "Enable sync between running Velivo instances on the same local network" },
            { "Synchronizuje ustawienia, zakładki, hasła, reguły prywatności i Szybki Dostęp dla tego samego profilu. Otwarte karty zostają na każdym komputerze osobno.", "Syncs settings, bookmarks, passwords, privacy rules and Quick Access for the same profile. Open tabs stay separate on each computer." },
            { "Włącz i zapisz synchronizację na obu komputerach. Sparuj je jednorazowo, porównując krótki kod; sekret zostanie zapisany lokalnie.", "Enable and save sync on both computers. Pair them once by comparing a short code; the secret is stored locally." },
            { "Sparuj urządzenie w sieci…", "Pair a device on the network…" },
            { "Zapisz plik odzyskiwania…", "Save recovery file…" },
            { "Odtwórz parowanie…", "Restore pairing…" },
            { "Tryb cichy LAN (bez dymków „Zsynchronizowano profil…”)", "Quiet LAN mode (no “Profile synced…” pop-ups)" },
            { "Log i panel diagnostyczny nadal działają, wyłączone są tylko wyskakujące komunikaty.", "The log and diagnostics panel still work; only pop-up messages are turned off." },
            { "Panel diagnostyczny LAN…", "LAN diagnostics panel…" },
            { "Zapisz", "Save" },
            { "Nie można używać tego folderu na śmieci:\n", "This junk folder cannot be used:\n" },
            { "Nie zapisano ustawień:\n", "Settings were not saved:\n" },
            { "Nowy folder na śmieci zacznie działać po ponownym uruchomieniu przeglądarki.", "The new junk folder will take effect after restarting the browser." },
            { "\nKliknij, aby przełączyć użytkownika/profil", "\nClick to switch user/profile" },
            { "Skrypt (JS) zablokowany regułą domeny", "Script (JS) blocked by domain rule" },
            { "Tracker zablokowany (reguła domeny)", "Tracker blocked (domain rule)" },
            { "Tracker zablokowany (AdBlock)", "Tracker blocked (AdBlock)" },
            { "Automatyczne czyszczenie danych domeny", "Automatic domain data clearing" },
            { "Cookies usunięte dla domeny (reguła)", "Cookies deleted for domain (rule)" },
            { "Godzina", "Time" },
            { "Domena", "Domain" },
            { "Powód", "Reason" },
            { "Tryb", "Mode" },
            { "Domena:", "Domain:" },
            { "Blokuj JavaScript dla domeny", "Block JavaScript for this domain" },
            { "Nie wysyłaj cookies dla domeny", "Don't send cookies for this domain" },
            { "Wymuś blokowanie trackerów dla domeny", "Force tracker blocking for this domain" },
            { "Automatycznie czyść dane po wejściu na domenę", "Automatically clear data when visiting this domain" },
            { "Zaufana domena (bez blokowania i SmartScreen)", "Trusted domain (no blocking and no SmartScreen)" },
            { "Reguły działają per domena. Karty prywatne używają osobnego, izolowanego storage WebView2 (InPrivate).", "Rules apply per domain. Private tabs use separate, isolated WebView2 storage (InPrivate)." },
            { "Prywat.", "Private" },
            { "Zwykły", "Normal" },
            { "Szybki Dostęp to wbudowany dodatek – jest zaufany na stałe i nic go nie blokuje. Nie trzeba dodawać reguły.", "Quick Access is a built-in extension – it is permanently trusted and nothing blocks it. No rule is needed." },
            { "Godzina: ", "Time: " },
            { "\nDomena: ", "\nDomain: " },
            { "\nPowód: ", "\nReason: " },
            { "\nTryb: ", "\nMode: " },
            { "Zapisz regułę", "Save rule" },
            { "Podaj poprawną domenę stron www, np. example.com (adresy chrome-extension:// dodatków nie są blokowane regułami).", "Enter a valid website domain, e.g. example.com (chrome-extension:// addresses are not blocked by rules)." },
            { "Domena: ", "Domain: " },
            { "Zapisać mimo to?", "Save anyway?" },
            { "Usuń regułę", "Delete rule" },
            { "Podaj poprawną domenę stron www, np. example.com", "Enter a valid website domain, e.g. example.com" },
            { "Zaufane domeny", "Trusted domains" },
            { "✔ Dodaj do zaufanych", "✔ Add to trusted" },
            { "✔ Zaznaczoną domenę do zaufanych", "✔ Trust selected domain" },
            { "Najpierw zaznacz wpis na liście blokad.", "First select an entry in the block list." },
            { "Wyczyść panel blokad", "Clear block list" },
            { "Więcej…", "More…" },
            { "Reguły prywatności dla domen", "Privacy rules for domains" },
            { "Zapisane reguły domen", "Saved domain rules" },
            { "Co zostało zablokowane i dlaczego", "What was blocked and why" },
            { "Wybierz wpis, aby zobaczyć pełny URL i szczegóły blokady.", "Select an entry to see the full URL and block details." },
            { "Szczegóły zaznaczonego wpisu", "Details of the selected entry" },
            { "Przełączyć profil na „", "Switch profile to “" },
            { "”?\nAplikacja uruchomi się ponownie z osobnym zestawem kart, historii i dodatków.", "”?\nThe app will restart with a separate set of tabs, history and extensions." },
            { "Profil", "Profile" },
            { "Użytkownicy i profile Velivo", "Velivo users and profiles" },
            { "Ikona profilu:", "Profile icon:" },
            { "Zapisz ikonkę", "Save icon" },
            { " (aktywny)", " (active)" },
            { "Dodaj użytkownika/profil…", "Add user/profile…" },
            { "Nazwa użytkownika/profilu (np. google-konto2):", "User/profile name (e.g. google-account2):" },
            { "Niepoprawna nazwa.", "Invalid name." },
            { "Profile", "Profiles" },
            { "Przełącz na zaznaczony", "Switch to selected" },
            { "Usuń zaznaczony profil", "Delete selected profile" },
            { "Nie można usunąć aktywnego ani domyślnego profilu.", "The active or default profile cannot be deleted." },
            { "Usunąć profil „", "Delete profile “" },
            { "” razem z jego lokalnymi danymi?", "” together with its local data?" },
            { "Każdy profil ma własne ustawienia, sesje, historię, zakładki i dodatki. Sejf oraz Szybki Dostęp pozostają wspólne i nie są tutaj zmieniane.", "Each profile has its own settings, sessions, history, bookmarks and extensions. Sejf and Quick Access stay shared and are not changed here." },
            { "Ta reguła może powodować utratę logowania i ustawień strony (cookies/sesja/localStorage).\n\n", "This rule may cause loss of logins and site settings (cookies/session/localStorage).\n\n" },
            { "Jasny (domyślny)", "Light (default)" },
            { "Grafit", "Graphite" },
            { "Granat", "Navy" },
            { "Nocny fiolet", "Night violet" },
            { "Las", "Forest" },
            { "Zachód słońca", "Sunset" },
            { "Czerń (OLED)", "Black (OLED)" },
            { "Papier", "Paper" },
            { "Mgła", "Mist" },
            { "Gosia (polski, naturalny offline)", "Gosia (Polish, natural offline)" },
            { "Darkman (polski, naturalny offline)", "Darkman (Polish, natural offline)" },
            { "MC Speech (polski, naturalny offline)", "MC Speech (Polish, natural offline)" },
            { "Lessac (angielski US, naturalny offline)", "Lessac (English US, natural offline)" },
            { "Ryan (angielski US, naturalny offline)", "Ryan (English US, natural offline)" },
            { "Alba (angielski UK, naturalny offline)", "Alba (English UK, natural offline)" },

            // ---- etapy 3-4: hasla, synchronizacja, pobieranie, okna pomocnicze ----
            { "Wystąpił nieoczekiwany błąd, ale Velivo działa dalej.\n\n", "An unexpected error occurred, but Velivo keeps running.\n\n" },
            { "\n\nSzczegóły zapisano w pliku bledy.log w folderze danych.", "\n\nDetails were saved to bledy.log in the data folder." },
            { "Wykryto wypełniony formularz adresowy.", "A filled-in address form was detected." },
            { "Wykryto dane karty płatniczej.", "Payment card data was detected." },
            { "\nZapisać lokalnie w szyfrowanej bazie offline Velivo?\n\nKod CVC nigdy nie jest zapisywany.", "\nSave locally in Velivo's encrypted offline database?\n\nThe CVC code is never saved." },
            { "Autouzupełnianie", "Autofill" },
            { "Brak zapisanych danych autouzupelniania.", "No saved autofill data." },
            { "Usunac wszystkie zapisane adresy z lokalnej bazy autouzupelniania?", "Delete all saved addresses from the local autofill database?" },
            { "Usunac wszystkie zapisane karty z lokalnej bazy autouzupelniania?", "Delete all saved cards from the local autofill database?" },
            { "\n• karty prywatne zostaną zamknięte,", "\n• private tabs will be closed," },
            { "\n• pobieranie zostanie wstrzymane (wznowisz je potem jednym kliknięciem),", "\n• downloads will be paused (resume them later with one click)," },
            { "Wyłączenie trybu ciemnego", "Turning off dark mode" },
            { " zadziała na wszystkich stronach po ponownym uruchomieniu Velivo.\nKarty wrócą same.", " will apply to all pages after restarting Velivo.\nTabs will come back." },
            { "\n\nUruchomić Velivo ponownie teraz?", "\n\nRestart Velivo now?" },
            { "Nie udało się uruchomić ponownie:\n", "Could not restart:\n" },
            { "Nie udało się zarejestrować Velivo w Windows:\n", "Could not register Velivo in Windows:\n" },
            { "Otworzyły się Ustawienia Windows.\n\nKliknij „Ustaw domyślne” przy Velivo (Windows 11)\nalbo wybierz Velivo jako „Przeglądarka sieci Web” (Windows 10).\n\nWindows nie pozwala programom zrobić tego samodzielnie.", "Windows Settings have opened.\n\nClick “Set default” next to Velivo (Windows 11)\nor choose Velivo as the “Web browser” (Windows 10).\n\nWindows does not let programs do this on their own." },
            { "Otwórz folder Pobrane", "Open Downloads folder" },
            { "Media na stronie", "Media on page" },
            { "Wyczyść zakończone", "Clear finished" },
            { "Za dużo przekierowań.", "Too many redirects." },
            { " z ", " of " },
            { "Serwer odpowiedział: ", "Server responded: " },
            { "Serwer nie obsługuje pobierania w częściach (", "The server does not support downloading in parts (" },
            { "Brak danych z serwera przez 60 s.", "No data from the server for 60 s." },
            { "Anulować pobieranie „", "Cancel download “" },
            { "”?\nPobrana część zostanie usunięta.", "”?\nThe downloaded part will be deleted." },
            { "Otwórz", "Open" },
            { "Pokaż w folderze", "Show in folder" },
            { "zostało ", "remaining " },
            { " połączeń", " connections" },
            { " (ten serwer nie pozwala wznowić – zacznie od nowa)", " (this server cannot resume – it will start over)" },
            { "Błąd: ", "Error: " },
            { " – kliknij „Wznów”, aby spróbować ponownie", " – click “Resume” to try again" },
            { "Wznów", "Resume" },
            { "Usuń z listy", "Remove from list" },
            { ").\n\nZamknąć Velivo?", ").\n\nClose Velivo?" },
            { "\nPliki pobierane przez silnik przeglądarki zostaną przerwane.", "\nFiles downloaded by the browser engine will be interrupted." },
            { " (pobiera silnik przeglądarki)", " (downloaded by the browser engine)" },
            { "Nie udało się wykonać operacji na pobieraniu:\n", "The download operation failed:\n" },
            { "🚫 Element zablokowany na ", "🚫 Element blocked on " },
            { ". Cofniesz to: prawy przycisk → Przywróć zablokowane elementy.", ". To undo: right-click → Restore blocked elements." },
            { "Przywrócono ", "Restored " },
            { " zablokowanych elementów na ", " blocked elements on " },
            { "Otwórz okienko dodatku", "Open extension popup" },
            { "Otwórz okienko w karcie", "Open popup in a tab" },
            { "Strona nowej karty", "New tab page" },
            { "Zarządzaj dodatkami…", "Manage extensions…" },
            { "Karta została zamknięta.", "The tab was closed." },
            { "” nie ma własnego okienka.\nDziała w tle i na stronach.", "” has no popup of its own.\nIt works in the background and on pages." },
            { "Nie udało się otworzyć okienka dodatku:\n", "Could not open the extension popup:\n" },
            { "Nie zapisano zakładek:\n", "Bookmarks were not saved:\n" },
            { "Otwórz w nowej karcie", "Open in new tab" },
            { "Zmień nazwę", "Rename" },
            { "Nazwa zakładki:", "Bookmark name:" },
            { "Usuń", "Delete" },
            { "Zakładki (dwuklik otwiera)", "Bookmarks (double-click opens)" },
            { "▲ W górę", "▲ Up" },
            { "▼ W dół", "▼ Down" },
            { "Brak dodatków. Kliknij „Wczytaj rozpakowany…” i wskaż folder z manifest.json.", "No extensions. Click “Load unpacked…” and choose the folder with manifest.json." },
            { "Włączony", "Enabled" },
            { "Usunąć dodatek „", "Remove extension “" },
            { "Strona ustawień dodatku", "Extension settings page" },
            { "Otwiera okienko dodatku w karcie", "Opens the extension popup in a tab" },
            { "Dodatek nie ma strony ustawień", "The extension has no settings page" },
            { "Przeładuj", "Reload" },
            { "Wczytuje dodatek od nowa z folderu (po zmianie jego plików). Dane dodatku zostają.", "Reloads the extension from its folder (after its files change). Extension data is kept." },
            { "Folder dodatku (z plikiem manifest.json)", "Extension folder (with manifest.json)" },
            { "W tym folderze nie ma pliku manifest.json.\nJeśli masz plik .crx lub .zip – rozpakuj go najpierw.", "There is no manifest.json in this folder.\nIf you have a .crx or .zip file – unpack it first." },
            { "Nie udało się wczytać dodatku:\n", "Could not load the extension:\n" },
            { "Otwórz Chrome Web Store", "Open Chrome Web Store" },
            { "Zainstaluj z linku/ID…", "Install from link/ID…" },
            { "Wklej link do dodatku z Chrome Web Store albo jego ID (32 litery):", "Paste a Chrome Web Store extension link or its ID (32 letters):" },
            { "To nie wygląda na link do dodatku ani na jego ID.", "This does not look like an extension link or ID." },
            { "Dodatki działają w tle i na stronach (skrypty treści, blokowanie, zmiana wyglądu). Silnik WebView2 nie pokazuje ikonek dodatków ani ich okienek popup – ustawienia otwierasz przyciskiem „Opcje”. Po dodaniu odśwież stronę.", "Extensions work in the background and on pages (content scripts, blocking, appearance changes). The WebView2 engine does not show extension icons or their popups – open settings with the “Options” button. Reload the page after adding." },
            { "Nie udało się pobrać ", "Could not download " },
            { " list(y) – używam poprzednich.", " list(s) – using the previous ones." },
            { "jeszcze nie pobrane", "not downloaded yet" },
            { "Dziś – ", "Today – " },
            { " strony", " pages" },
            { "Szukaj w tytułach i adresach", "Search titles and addresses" },
            { "🔍 Szukaj w historii…", "🔍 Search history…" },
            { "Usuń z historii", "Delete from history" },
            { "Usuń znalezione wpisy z tego dnia", "Delete found entries from this day" },
            { "Usuń cały dzień z historii", "Delete the whole day from history" },
            { "Usunąć historię z tego dnia?", "Delete history from this day?" },
            { "● Bieżąca sesja  ", "● Current session  " },
            { "Otwórz wszystkie w nowych kartach", "Open all in new tabs" },
            { "Otworzyć ", "Open " },
            { "Usuń sesję z historii", "Delete session from history" },
            { "Usunąć tę sesję z historii?", "Delete this session from history?" },
            { "Nic nie znaleziono.", "Nothing found." },
            { "Historia jest pusta.", "History is empty." },
            { "Wyczyść całą historię", "Clear all history" },
            { "Usunąć całą historię?", "Delete all history?" },
            { "Dwuklik otwiera stronę · prawy klik: więcej opcji", "Double-click opens the page · right-click: more options" },
            { "Włącz synchronizację LAN, zapisz ustawienia i otwórz je ponownie, aby rozpocząć parowanie.", "Enable LAN sync, save settings and open them again to start pairing." },
            { "Trwa już próba parowania. Zakończ ją albo poczekaj na wygaśnięcie.", "A pairing attempt is already in progress. Finish it or wait for it to expire." },
            { "Wysłano prośbę o parowanie; oczekuję na potwierdzenie drugiego urządzenia.", "Pairing request sent; waiting for the other device to confirm." },
            { "Prośba o parowanie LAN została wysłana.", "The LAN pairing request was sent." },
            { "Nie udało się obsłużyć parowania: ", "Could not handle pairing: " },
            { "Odrzucono prośbę o parowanie z innego profilu.", "Rejected a pairing request from a different profile." },
            { "Urządzenie ", "Device " },
            { ") chce sparować profil „", ") wants to pair profile “" },
            { "Na obu komputerach musi być widoczny ten sam kod: ", "Both computers must show the same code: " },
            { "Po sparowaniu urządzenia będą synchronizować także zapisane hasła. Czy akceptujesz?", "After pairing, the devices will also sync saved passwords. Do you accept?" },
            { "Potwierdź parowanie Velivo", "Confirm Velivo pairing" },
            { "Odrzucono prośbę o parowanie od ", "Rejected pairing request from " },
            { "Zaakceptowano prośbę od ", "Accepted request from " },
            { "; oczekiwanie na zakończenie parowania.", "; waiting for pairing to finish." },
            { "Potwierdź sparowanie z ", "Confirm pairing with " },
            { "Porównaj kod z drugim komputerem: ", "Compare the code with the other computer: " },
            { "Akceptuj tylko wtedy, gdy kody są identyczne. Sparowanie zastąpi obecny klucz LAN; pozostałe urządzenia trzeba będzie sparować ponownie.", "Accept only if the codes are identical. Pairing replaces the current LAN key; other devices will need to be paired again." },
            { "Anulowano parowanie z ", "Pairing cancelled with " },
            { "Potwierdzono kod z ", "Code confirmed with " },
            { "; wysłano zaszyfrowany klucz synchronizacji.", "; encrypted sync key sent." },
            { "Parowanie z ", "Pairing with " },
            { " zakończone. Klucz zapisano lokalnie.", " finished. The key was saved locally." },
            { "Nieprawidłowe dane parowania.", "Invalid pairing data." },
            { "Nieprawidłowy klucz synchronizacji.", "Invalid sync key." },
            { "Połączono z ", "Connected to " },
            { ".\n\nZakładki, hasła i Szybki Dostęp zostaną POŁĄCZONE z obu komputerów – nic nie zginie.\n\n", ".\n\nBookmarks, passwords and Quick Access will be MERGED from both computers – nothing will be lost.\n\n" },
            { "Ustawienia przeglądarki (wygląd, wyszukiwarka, prywatność itd.):\n", "Browser settings (appearance, search engine, privacy etc.):\n" },
            { "• Tak – zachowaj ustawienia z TEGO komputera\n• Nie – przyjmij ustawienia z ", "• Yes – keep settings from THIS computer\n• No – take settings from " },
            { "Próba parowania wygasła.", "The pairing attempt expired." },
            { "Nieznane urządzenie", "Unknown device" },
            { "Najpierw sparuj urządzenie lub skonfiguruj synchronizację LAN.", "First pair a device or set up LAN sync." },
            { "Zapisz zaszyfrowany plik odzyskiwania", "Save encrypted recovery file" },
            { "Ustaw hasło do pliku odzyskiwania (co najmniej 12 znaków):", "Set a password for the recovery file (at least 12 characters):" },
            { "Hasło musi mieć co najmniej 12 znaków.", "The password must have at least 12 characters." },
            { "Wpisz ponownie hasło do pliku odzyskiwania:", "Enter the recovery file password again:" },
            { "Hasła nie są identyczne.", "The passwords do not match." },
            { "Plik odzyskiwania został zapisany. Przechowuj go poza tym komputerem.", "The recovery file was saved. Keep it outside this computer." },
            { "Nie udało się zapisać pliku odzyskiwania:\n", "Could not save the recovery file:\n" },
            { "Odtwórz parowanie z pliku recovery", "Restore pairing from recovery file" },
            { "Wpisz hasło do pliku odzyskiwania:", "Enter the recovery file password:" },
            { "Plik odzyskiwania przekracza limit 1 MB.", "The recovery file exceeds the 1 MB limit." },
            { "Nieobsługiwana lub nieprawidłowa wersja pliku odzyskiwania.", "Unsupported or invalid recovery file version." },
            { "Nieprawidłowy rozmiar danych pliku odzyskiwania.", "Invalid recovery file data size." },
            { "Plik nie zawiera prawidłowego klucza parowania.", "The file does not contain a valid pairing key." },
            { "Parowanie odtworzono. Synchronizacja LAN jest aktywna.", "Pairing restored. LAN sync is active." },
            { "Hasło jest nieprawidłowe albo plik odzyskiwania jest uszkodzony.", "The password is wrong or the recovery file is damaged." },
            { "Nie udało się odtworzyć parowania:\n", "Could not restore pairing:\n" },
            { "LAN sync uruchomiona na porcie ", "LAN sync started on port " },
            { "LAN sync uruchomiona w trybie zgodności bez klucza (profil: ", "LAN sync started in compatibility mode without a key (profile: " },
            { "Błąd startu LAN sync: ", "LAN sync start error: " },
            { "Błąd odbioru LAN: ", "LAN receive error: " },
            { "Wykryto urządzenie: ", "Device detected: " },
            { "Dołączyłeś do sieci z innym trybem pracy.", "You joined the network with a different profile." },
            { "Wykryto zmianę trybu pracy na innym urządzeniu.", "A profile change was detected on another device." },
            { "\n\nUrządzenie: ", "\n\nDevice: " },
            { "\n\nPrzełączyć się na profil \"", "\n\nSwitch to profile \"" },
            { "\", aby zachować synchronizację LAN?", "\" to keep LAN sync?" },
            { "Nie wysłano pakietu LAN: przekracza limit UDP (", "LAN packet not sent: exceeds the UDP limit (" },
            { "Błąd nadawania LAN: ", "LAN send error: " },
            { "🌐 Zsynchronizowano z Velivo w sieci lokalnej.", "🌐 Synced with Velivo on the local network." },
            { "Zsynchronizowano z ", "Synced with " },
            { " (ustawienia przyjęte)", " (settings accepted)" },
            { ", zakładki połączone.", ", bookmarks merged." },
            { "Błąd importu LAN: ", "LAN import error: " },
            { "W sieci jest drugi Velivo:\n\nUrządzenie: ", "Another Velivo is on the network:\n\nDevice: " },
            { "\n\nPołączyć oba komputery i synchronizować wszystko – ustawienia, zakładki, karty, hasła i Szybki Dostęp?", "\n\nConnect both computers and sync everything – settings, bookmarks, passwords and Quick Access?" },
            { "\n\nNa obu ekranach pojawi się ten sam krótki kod do porównania. Dane będą szyfrowane.", "\n\nBoth screens will show the same short code to compare. Data will be encrypted." },
            { "Odrzucono pakiety z ", "Rejected packets from " },
            { ": zegar różni się o ", ": clock differs by " },
            { " min. Ustaw automatyczny czas w Windows na obu komputerach.", " min. Turn on automatic time in Windows on both computers." },
            { "Odśwież teraz", "Refresh now" },
            { "Wyczyść log", "Clear log" },
            { "Wykryte urządzenia", "Detected devices" },
            { "Status: synchronizacja LAN wyłączona", "Status: LAN sync off" },
            { "Status: aktywna, ale brak połączonych urządzeń", "Status: active, but no devices connected" },
            { "Status: połączono z ", "Status: connected to " },
            { " urządzeniem/urządzeniami", " device(s)" },
            { "   Błędy: ", "   Errors: " },
            { "Brak aktywnych peerów.", "No active peers." },
            { "Nie udało się uruchomić WebView2:\n", "Could not start WebView2:\n" },
            { "Nie udało się otworzyć karty.\nJeśli działa jeszcze starsza wersja Velivo, zamknij ją i spróbuj ponownie.\n\n", "Could not open the tab.\nIf an older version of Velivo is still running, close it and try again.\n\n" },
            { "Wykryto media do pobrania na stronie: ", "Downloadable media detected on the page: " },
            { "Pokaż", "Show" },
            { "Zamknij", "Close" },
            { "Na YouTube Velivo nie udostępnia pobierania wideo/audio.\n\n", "Velivo does not offer video/audio downloads on YouTube.\n\n" },
            { "Na innych stronach (bez DRM) wykrywanie i pobieranie działa normalnie.", "On other sites (without DRM) detection and downloading work normally." },
            { "Wykryte media na stronie", "Media detected on the page" },
            { "🎬 Nie wykryto źródeł audio/wideo na tej stronie.", "🎬 No audio/video sources detected on this page." },
            { "Pobierz", "Download" },
            { "Pobierz jako audio", "Download as audio" },
            { "Nie udało się wykryć mediów:\n", "Could not detect media:\n" },
            { "To źródło jest typu blob (tymczasowe dane w pamięci strony), więc nie da się go pobrać bezpośrednio jako pliku.", "This source is a blob (temporary data in page memory), so it cannot be downloaded directly as a file." },
            { "To źródło nie jest bezpośrednim adresem HTTP/HTTPS do pliku.", "This source is not a direct HTTP/HTTPS file address." },
            { "Dla YouTube pobieranie nie jest wspierane w Velivo z uwagi na zasady platformy i prawa autorskie.\n\n", "Downloading from YouTube is not supported in Velivo because of the platform's rules and copyright.\n\n" },
            { "🎬 Dodano do pobierania: ", "🎬 Added to downloads: " },
            { "Nie udało się przejąć tego pobierania.\nStrona może wymagać tokenu sesji lub odtwarzacz używa szyfrowanego streamu.", "Could not take over this download.\nThe page may require a session token or the player uses an encrypted stream." },
            { "Import haseł", "Import passwords" },
            { "Zaimportowano wpisów: ", "Entries imported: " },
            { "Hasła", "Passwords" },
            { "Eksport haseł", "Export passwords" },
            { "Ten wpis nie zawiera adresu strony WWW. Zaimportowany link aplikacji Android nie może być otwarty w przeglądarce. Uzupełnij pole URL adresem https://...", "This entry has no website address. An imported Android app link cannot be opened in the browser. Fill in the URL field with https://..." },
            { "Wykryto nowe hasło dla ", "New password detected for " },
            { " na ", " on " },
            { ".\nZaktualizować wpis w bazie Velivo?", ".\nUpdate the entry in the Velivo database?" },
            { "Wykryto hasło na stronie ", "Password detected on " },
            { ".\nDodać do bazy Velivo?", ".\nAdd to the Velivo database?" },
            { "Dodaj wpis hasła", "Add password entry" },
            { "Edytuj wpis hasła", "Edit password entry" },
            { "Generuj mocne hasło", "Generate strong password" },
            { "Wklej ze schowka", "Paste from clipboard" },
            { "Użytkownik:", "Username:" },
            { "Hasło:", "Password:" },
            { "Hasło nie może być puste.", "The password cannot be empty." },
            { "Menedżer haseł Velivo", "Velivo password manager" },
            { "Szukaj po domenie, loginie lub nazwie", "Search by domain, login or name" },
            { "Użytkownik", "Username" },
            { "Źródło", "Source" },
            { "Wpisów: ", "Entries: " },
            { "\nUżytkownik: ", "\nUsername: " },
            { "\nHasło: ", "\nPassword: " },
            { "Dodaj", "Add" },
            { "Usuń zaznaczone", "Delete selected" },
            { "Usunąć zaznaczone wpisy: ", "Delete selected entries: " },
            { "Kopiuj login", "Copy login" },
            { "Kopiuj hasło", "Copy password" },
            { "Pokaż/ukryj hasło", "Show/hide password" },
            { "Usuń wszystkie zapisane hasła", "Delete all saved passwords" },
            { "Usunąć hurtowo wszystkie hasła z lokalnej bazy Velivo?\nOperacji nie da się cofnąć.", "Delete all passwords from the local Velivo database?\nThis cannot be undone." },
            { "Usunięto wpisów: ", "Entries deleted: " },
            { "🔊 Trwa pobieranie głosu – chwilę…", "🔊 Downloading the voice – one moment…" },
            { "głos ", "voice " },
            { "✅ Głos ", "✅ Voice " },
            { " gotowy – działa bez internetu.", " ready – works offline." },
            { "❌ Nie udało się pobrać głosu Piper: ", "❌ Could not download the Piper voice: " },
            { "\nCzytam głosem systemowym.", "\nReading with the system voice." },
            { "Transfer grafik Szybkiego Dostępu LAN niedostępny: ", "Quick Access LAN image transfer unavailable: " },
            { "Nie udało się przygotować Szybkiego Dostępu do synchronizacji: ", "Could not prepare Quick Access for sync: " },
            { "Nie udało się wysłać grafik Szybkiego Dostępu do ", "Could not send Quick Access images to " },
            { ". Sprawdź zaporę LAN.", ". Check the LAN firewall." },
            { "Zsynchronizowano skróty i grafiki Szybkiego Dostępu z ", "Quick Access shortcuts and images synced with " },
            { "🔊 Nie znalazłem tekstu do przeczytania na tej stronie.", "🔊 No text to read was found on this page." },
            { "\nKliknij: pauza / wznów (Ctrl+Shift+U)", "\nClick: pause / resume (Ctrl+Shift+U)" },
            { "Czytaj stronę na głos (Ctrl+Shift+U)\nZaznacz tekst, aby przeczytać tylko fragment", "Read page aloud (Ctrl+Shift+U)\nSelect text to read only part of it" },
            { "📰 Za mało treści do trybu czytania na tej stronie.", "📰 Not enough content for reader mode on this page." },
            { "Czytaj podsumowanie", "Read summary" },
            { "Czytaj całość", "Read all" },
            { "Zatrzymaj", "Stop" },
            { "Głośność czytania", "Reading volume" },
            { "Nie udało się uruchomić czytnika:\n", "Could not start the reader:\n" },
            { "Nie udało się uruchomić trybu czytania:\n", "Could not start reader mode:\n" },
            { "Brak danych do streszczenia.", "No data to summarize." },
            { "Pokaz w folderze", "Show in folder" },
            { "Otwórz folder ze zrzutami", "Open screenshots folder" },
            { "całej strony", "of the full page" },
            { "widocznej części", "of the visible part" },
            { " i skopiowano do schowka.", " and copied to the clipboard." },
            { "Nie udało się zrobić zrzutu ekranu:\n", "Could not take a screenshot:\n" },
            { "\nKliknij, aby wypełnić formularz", "\nClick to fill in the form" },
            { "🔑 Nie znaleziono pola loginu lub hasła na tej stronie.", "🔑 No login or password field found on this page." },
            { "Zapisz paczkę synchronizacji", "Save sync package" },
            { "Paczka przekracza limit 64 MB. Zmniejsz liczbę miniaturek w Szybkim Dostępie.", "The package exceeds the 64 MB limit. Reduce the number of thumbnails in Quick Access." },
            { "Nie udało się wyeksportować synchronizacji:\n", "Could not export sync:\n" },
            { "Wczytaj paczkę synchronizacji", "Load sync package" },
            { "Niepoprawna zawartość paczki.", "Invalid package content." },
            { "nieznane urządzenie", "unknown device" },
            { "Ta starsza paczka nie zawiera identyfikatora urządzenia.", "This older package has no device identifier." },
            { "To urządzenie było już wcześniej rozpoznane.", "This device was recognized before." },
            { "To nowe urządzenie zostanie zapamiętane po imporcie.", "This new device will be remembered after import." },
            { "\n\nImport zastąpi lokalne ustawienia, zakładki, historię, sesję, reguły i sejf haseł. Skróty Szybkiego Dostępu Velivo i ich grafiki zostaną scalone z lokalnymi. Kontynuować?", "\n\nThe import will replace local settings, bookmarks, history, session, rules and the password vault. Velivo Quick Access shortcuts and their images will be merged with local ones. Continue?" },
            { "Potwierdź import synchronizacji", "Confirm sync import" },
            { "Wczytano paczkę od ", "Loaded package from " },
            { ". Urządzenie zostało zapamiętane. Dla pełnego efektu uruchom ponownie przeglądarkę.", ". The device was remembered. Restart the browser for the full effect." },
            { "Niepoprawny kod dostępu albo uszkodzona paczka.", "Wrong access code or damaged package." },
            { "Nie udało się wczytać synchronizacji:\n", "Could not load sync:\n" },
            { "Kopiuj kod", "Copy code" },
            { "Paczka nie wygasa. Przenieś ją przez EchoSync; na drugim komputerze wybierz Importuj paczkę i wpisz ten kod. Zachowaj kod osobno, nie jest zapisany w pliku.", "The package does not expire. Move it with EchoSync; on the other computer choose Import package and enter this code. Keep the code separately – it is not stored in the file." },
            { "Kod dostępu do paczki", "Package access code" },
            { "Wpisz kod dostępu wyświetlony przy eksporcie paczki:", "Enter the access code shown when the package was exported:" },
            { "Nieobsługiwana wersja paczki synchronizacji.", "Unsupported sync package version." },
            { "Nieprawidłowe parametry paczki synchronizacji.", "Invalid sync package parameters." },
            { "Nieprawidłowy rozmiar danych w paczce synchronizacji.", "Invalid data size in the sync package." },
            { "⏳ Instaluję…", "⏳ Installing…" },
            { "Paczka nie zawiera pliku manifest.json.", "The package does not contain manifest.json." },
            { "”.\nOdśwież strony, na których ma działać.\nZarządzasz nim w oknie 🧩.", "”.\nReload the pages where it should work.\nManage it in the 🧩 window." },
            { "Nie udało się pobrać dodatku ze sklepu.\nSprawdź połączenie z internetem – albo dodatek został wycofany.\n\n", "Could not download the extension from the store.\nCheck your internet connection – or the extension was withdrawn.\n\n" },
            { "Nie udało się zainstalować dodatku:\n", "Could not install the extension:\n" },
            { "\n\nNiektóre dodatki wymagają funkcji pełnego Chrome, których silnik WebView2 nie ma.", "\n\nSome extensions need full Chrome features that the WebView2 engine lacks." },
            { "Serwer nie zwrócił paczki dodatku (CRX).", "The server did not return the extension package (CRX)." },
            { "Pobieranie", "Downloads" },
            { "Opcje", "Options" },
            { "Nazwa", "Name" },
            { "Adres", "Address" },
            { "Wczytaj rozpakowany…", "Load unpacked…" },
            { "Data", "Date" },
            { "Zainstalowano dodatek „", "Installed extension “" },

            // ---- dopiski ----
            { "\n\nStrona: ", "\n\nPage: " },
            { "Karta", "Card" },
            { "Zapisane dane autouzupelniania", "Saved autofill data" },
            { "Usunieto pozycji adresowych: ", "Address entries deleted: " },
            { "Autouzupelnianie", "Autofill" },
            { "Usunieto pozycji kart: ", "Card entries deleted: " },
            { "\n\nUwaga:", "\n\nNote:" },
            { "Pobrane pliki – Velivo", "Downloads – Velivo" },
            { "Wstrzymaj", "Pause" },
            { "Pobrane", "Downloads" },
            { "Wstrzymano – ", "Paused – " },
            { "Gotowe – ", "Done – " },
            { "Anulowano", "Cancelled" },
            { "\nPobieranie zostanie wstrzymane – wznowisz je po ponownym uruchomieniu.", "\nDownloads will be paused – you can resume them after restarting." },
            { "Przerwano – ", "Interrupted – " },
            { "Przerwano (", "Interrupted (" },
            { "Dodatek „", "Extension “" },
            { "Dodatki – tryb dewelopera", "Extensions – developer mode" },
            { "Okienko", "Popup" },
            { "Wczoraj – ", "Yesterday – " },
            { "Sesja  ", "Session  " },
            { "Znaleziono: ", "Found: " },
            { "Razem: ", "Total: " },
            { "Dalej", "Next" },
            { "Odzyskiwanie parowania LAN", "LAN pairing recovery" },
            { "\nWykryty profil: ", "\nDetected profile: " },
            { "\nAktualny profil: ", "\nCurrent profile: " },
            { "Odrzucono niekompletny stan synchronizacji.", "Rejected an incomplete sync state." },
            { "\nProfil: ", "\nProfile: " },
            { "Log synchronizacji", "Sync log" },
            { "Diagnostyka synchronizacji LAN", "LAN sync diagnostics" },
            { "Status: synchronizacja LAN nieaktywna", "Status: LAN sync inactive" },
            { "Profil: ", "Profile: " },
            { "   Ostatni TX: ", "   Last TX: " },
            { "Wyeksportowano.", "Exported." },
            { "\nNazwa: ", "\nName: " },
            { "\nNotatki: ", "\nNotes: " },
            { "Edytuj", "Edit" },
            { "Import CSV…", "Import CSV…" },
            { "Eksport CSV…", "Export CSV…" },
            { "Czytanie: zdanie ", "Reading: sentence " },
            { "Tryb czytania – ", "Reader mode – " },
            { "Paczka od: ", "Package from: " },
            { "Gotowe", "Done" },
            { "Odszyfruj", "Decrypt" },
            { "Import paczki synchronizacji", "Import sync package" },
            { "   Ostatni RX: ", "   Last RX: " },
            { "Dodatek nie ma okienka", "The extension has no popup" },

            { " kart?", " tabs?" },
            { "Nazwa:", "Name:" },
            { "URL / strona:", "URL / site:" },
            { "Notatki:", "Notes:" },
            { "Ochrona przed śledzeniem:", "Tracking prevention:" },
            { "Ochrona zrównoważona (zalecana)", "Balanced protection (recommended)" },
            { "Ścisła ochrona", "Strict protection" },
            { "Zrównoważona: blokuje znane trackery, a osadzone treści (np. wpisy z X, filmy) działają. Ścisła: blokuje też osadzone treści serwisów społecznościowych. Na zaufanych domenach ścisła działa jak zrównoważona, chyba że zaznaczysz dla domeny „Wymuś blokowanie trackerów”.", "Balanced: blocks known trackers while embedded content (e.g. posts from X, videos) still works. Strict: also blocks embedded social media content. On trusted domains strict works like balanced, unless you tick \"Force tracker blocking for this domain\"." },
            { "Odepnij z paska (dodatek dalej działa)", "Unpin from toolbar (extension keeps working)" },
            { "Przypnij do paska", "Pin to toolbar" },
            { "Brak włączonych dodatków", "No enabled extensions" },
            { "Przypnij kartę", "Pin tab" },
            { "Odepnij kartę", "Unpin tab" },
            { "Wytnij", "Cut" },
            { "Kopiuj", "Copy" },
            { "Wklej", "Paste" },
            { "Wklej i przejdź", "Paste and go" },
            { "Zaznacz wszystko", "Select all" },
            { "Otwieraj linki w tej samej karcie", "Open links in the same tab" },
            { "Linki, które strona chce otworzyć w nowej karcie, otwierają się w bieżącej - działa Wstecz i Dalej. Ctrl+klik dalej otwiera nową kartę. Wyłączone: jak w innych przeglądarkach.", "Links a page wants to open in a new tab open in the current one, so Back and Forward work. Ctrl+click still opens a new tab. Off: like other browsers." },
            { "Plik usunięty lub przeniesiony", "File deleted or moved" },
            { "Usuń tę stronę z historii dnia", "Remove this site from the day's history" },
            { "Włącz dźwięk karty", "Unmute tab" },
            { "Wycisz kartę", "Mute tab" },
            { "Odświeżaj automatycznie", "Auto refresh" },
            { "Wyłączone", "Off" },
            { "Zestawy kart", "Tab sets" },
            { "Zapisz otwarte karty jako zestaw…", "Save open tabs as a set…" },
            { "Nazwa zestawu (np. Praca, Zakupy):", "Set name (e.g. Work, Shopping):" },
            { "Otwórz wszystkie karty", "Open all tabs" },
            { "Zastąp obecnymi kartami", "Replace with current tabs" },
            { "Usuń zestaw", "Delete set" },
            { "Dodaj do grupy", "Add to group" },
            { "Nowa grupa…", "New group…" },
            { "Usuń z grupy", "Remove from group" },
            { "Nazwa grupy:", "Group name:" },
            { "Zmień nazwę grupy…", "Rename group…" },
            { "Kolor", "Color" },
            { "Rozgrupuj (karty zostają)", "Ungroup (tabs stay)" },
            { "Zamknij wszystkie karty grupy", "Close all tabs in group" },
            { "Kliknij, aby zwinąć lub rozwinąć grupę · prawy przycisk: więcej opcji", "Click to collapse or expand the group · right-click: more options" },
            { "niebieski", "blue" },
            { "zielony", "green" },
            { "pomarańczowy", "orange" },
            { "fioletowy", "purple" },
            { "czerwony", "red" },
            { "morski", "teal" },
            { "różowy", "pink" },
            { "szary", "gray" },
            { "Szukaj w kartach (Ctrl+Shift+A)", "Search tabs (Ctrl+Shift+A)" },
            { "Szukaj w kartach", "Search tabs" },
            { "Obraz w obrazie", "Picture in picture" },
            { "⧉ Obraz w obrazie", "⧉ Picture in picture" },
            { "Na tej stronie nie ma filmu. Filmy w ramkach (np. osadzony YouTube) mają przycisk ⧉ po najechaniu myszką.", "There is no video on this page. Videos in frames (e.g. embedded YouTube) show a ⧉ button on hover." },
            { "🍪 Nie odrzucaj banerów ciasteczek na tej stronie", "🍪 Don't reject cookie banners on this site" },
            { "🍪 Odrzucaj banery ciasteczek na tej stronie", "🍪 Reject cookie banners on this site" },
            { "Ciasteczka", "Cookies" },
            { "  (baner zgody odrzucony)", "  (consent banner rejected)" },
            { "Automatycznie odrzucaj banery z ciasteczkami (RODO)", "Automatically reject cookie banners (GDPR)" },
            { "Velivo samo klika „Odrzuć” albo „Tylko niezbędne”. Gdy baner nie ma takiego przycisku, nic nie jest klikane. Wyjątek dla strony: prawy przycisk na stronie.", "Velivo clicks \"Reject\" or \"Only necessary\" for you. If a banner has no such button, nothing is clicked. Per-site exception: right-click on the page." },
            { "Skróty wyszukiwania (np. „yt koty”)…", "Search shortcuts (e.g. \"yt cats\")…" },
            { "Skróty wyszukiwania", "Search shortcuts" },
            { "Jeden skrót w linii: skrót=adres, gdzie %s to szukany tekst. Przykład: wpisz w pasku adresu „yt koty”, a otworzy się wyszukiwanie „koty” na YouTube.", "One shortcut per line: shortcut=address, where %s is the search text. Example: type \"yt cats\" in the address bar to search YouTube for \"cats\"." },
            { "Przywróć domyślne", "Restore defaults" },
            { "Gesty myszy (prawy przycisk + ruch)", "Mouse gestures (right button + move)" },
            { "Przytrzymaj prawy przycisk i przesuń: ← wstecz, → dalej, ↑ nowa karta, ↓ zamknij kartę, ↓→ odśwież. Zwykły prawy klik otwiera menu jak zawsze.", "Hold the right button and move: ← back, → forward, ↑ new tab, ↓ close tab, ↓→ reload. A normal right-click opens the menu as always." },
            { "Przycisk „Obraz w obrazie” nad filmami", "\"Picture in picture\" button over videos" },
            { "Po najechaniu myszką na film pojawia się przycisk ⧉ – film przechodzi do małego okienka zawsze na wierzchu.", "Hovering over a video shows a ⧉ button – the video moves to a small always-on-top window." },
            { "🧠 Gdzie ja to czytałem?", "🧠 Where did I read that?" },
            { "🧠 Gdzie ja to czytałem? (Ctrl+Shift+F)", "🧠 Where did I read that? (Ctrl+Shift+F)" },
            { "🧠 Szukaj w treści stron…", "🧠 Search page contents…" },
            { "Wyczyść pamięć stron", "Clear page memory" },
            { "  ·  zapamiętywanie jest wyłączone w ustawieniach", "  ·  remembering is turned off in settings" },
            { "Usuń z pamięci", "Remove from memory" },
            { "Usunąć całą zapamiętaną treść stron?", "Delete all remembered page contents?" },
            { "⏱ Fałszywy licznik – po odświeżeniu strony odlicza od nowa: ", "⏱ Fake countdown – it restarts after reloading the page: " },
            { "⏱ Licznik odliczający presję czasu (odśwież stronę – jeśli zacznie od nowa, jest fałszywy): ", "⏱ Countdown creating time pressure (reload the page – if it restarts, it's fake): " },
            { "📦 Presja „ostatnich sztuk”: ", "📦 \"Last items\" pressure: " },
            { "👥 Presja „inni właśnie kupują / oglądają”: ", "👥 \"Others are buying / watching now\" pressure: " },
            { "☑ Zaznaczony z góry dodatek – Velivo go odznaczyło: ", "☑ Pre-ticked add-on – Velivo unticked it: " },
            { "💸 Dodatkowa opłata pojawiająca się przy zamówieniu: ", "💸 Extra fee appearing at checkout: " },
            { "Takie elementy mają skłonić do szybkiego zakupu bez zastanowienia. Nie musisz się spieszyć – sprawdź cenę gdzie indziej i wróć, kiedy chcesz.", "These elements push you to buy quickly without thinking. You don't have to hurry – compare prices elsewhere and come back when you want." },
            { "Sztuczki presji w sklepie", "Shop pressure tricks" },
            { "📺 Wyślij do…", "📺 Send to…" },
            { "Włącz i sparuj synchronizację LAN w ustawieniach", "Turn on and pair LAN sync in settings" },
            { "Brak innych Velivo w sieci (muszą być włączone)", "No other Velivo on the network (they must be running)" },
            { "Tej karty nie da się wysłać (to nie jest zwykła strona).", "This tab can't be sent (it isn't a regular web page)." },
            { "🧾 Paragon prywatności tej strony", "🧾 Privacy receipt for this page" },
            { "Strona nie łączyła się z żadną zewnętrzną firmą.", "The page didn't connect to any outside company." },
            { "Nie wykryto prób rozpoznania komputera (fingerprinting).", "No attempts to identify your computer (fingerprinting) were detected." },
            { "Nie wykryto znanych brokerów danych.", "No known data brokers detected." },
            { "Zapamiętuj treść przeczytanych stron (szukanie: Ctrl+Shift+F)", "Remember the text of pages you read (search: Ctrl+Shift+F)" },
            { "„Gdzie ja to czytałem?” – tekst stron zostaje tylko na tym komputerze. Pomijane są karty prywatne, banki, płatności, poczta i strony z polem hasła.", "\"Where did I read that?\" – page text stays only on this computer. Private tabs, banks, payments, mail and pages with a password field are skipped." },
            { "Ostrzegaj przed sztuczkami presji w sklepach", "Warn about pressure tricks in shops" },
            { "Fałszywe liczniki, „ostatnie sztuki”, „X osób ogląda”, zaznaczone z góry dodatki (Velivo je odznacza) i ukryte opłaty.", "Fake countdowns, \"last items\", \"X people are watching\", pre-ticked add-ons (Velivo unticks them) and hidden fees." },
            { "Paragon prywatności na tarczy", "Privacy receipt on the shield" },
            { "Po kliknięciu tarczy: z iloma firmami i krajami łączyła się strona, brokerzy danych i próby rozpoznania komputera.", "Click the shield to see how many companies and countries the page connected to, data brokers and fingerprinting attempts." },
            { "🔊 Czytaj od tego miejsca", "🔊 Read from here" },
            { "🔊 W tym miejscu nie ma tekstu do przeczytania – kliknij prawym przyciskiem na akapicie.", "🔊 There is no text to read here – right-click on a paragraph." },
            { "Styl wyglądu:", "Look:" },
            { "Nowoczesny (spokojny, jak Windows 11)", "Modern (calm, like Windows 11)" },
            { "Kolorowy (kolorowe przyciski)", "Colorful (colored buttons)" },
            { "Najważniejsze zdania (streszczenie lokalne, bez AI):", "Key sentences (local summary, no AI):" },
            { "🖥 Wróć do wersji komputerowej tej strony", "🖥 Back to the desktop version of this site" },
            { "📱 Pokaż wersję telefonu tej strony", "📱 Show the phone version of this site" },
            { "⬇ Pobierz film…", "⬇ Download video…" },
            { "Pobierz film", "Download video" },
            { "Najlepsza jakość wideo (do 1080p, MP4)", "Best video quality (up to 1080p, MP4)" },
            { "  – dobierze dodatek FFmpeg", "  – will add FFmpeg" },
            { "Szybko: wideo w jednym pliku (zwykle 360p–720p, bez dodatków)", "Quick: video in one file (usually 360p–720p, no extras)" },
            { "Tylko dźwięk (M4A, bez dodatków)", "Audio only (M4A, no extras)" },
            { "Tylko dźwięk MP3", "Audio only MP3" },
            { "Pobieraj tylko materiały, do których masz prawo (np. na własny użytek). Treści zabezpieczone DRM (Netflix, Disney+ itp.) nie są obsługiwane.", "Only download content you have the right to (e.g. for personal use). DRM-protected content (Netflix, Disney+ etc.) is not supported." },
            { "Do pobierania z YouTube i innych serwisów Velivo używa darmowego narzędzia yt-dlp (ok. 18 MB, z serwisu GitHub).\n\nPobrać je teraz? To jednorazowe.", "To download from YouTube and other sites Velivo uses the free yt-dlp tool (about 18 MB, from GitHub).\n\nDownload it now? This is a one-time step." },
            { "Najlepsza jakość i MP3 wymagają darmowego dodatku FFmpeg (ok. 140 MB do pobrania, po rozpakowaniu ok. 130 MB).\n\nPobrać go teraz? To jednorazowe.", "Best quality and MP3 need the free FFmpeg add-on (about 140 MB download, about 130 MB unpacked).\n\nDownload it now? This is a one-time step." },
            { "Nie udało się rozpakować FFmpeg:\n", "Could not unpack FFmpeg:\n" },
            { "Przygotowanie…", "Preparing…" },
            { "Nie udało się pobrać: ", "Download failed: " },
            { "🎬 Pobrano: ", "🎬 Downloaded: " },
            { "Przycisk „Pobierz” nad filmami", "\"Download\" button over videos" },
            { "Jak Internet Download Manager: po najechaniu na film pojawia się ⬇ Pobierz. Zwykłe pliki pobiera menedżer Velivo (do 16 połączeń), YouTube i strumienie – darmowe narzędzie yt-dlp.", "Like Internet Download Manager: hover over a video to see ⬇ Download. Regular files go through Velivo's manager (up to 16 connections), YouTube and streams through the free yt-dlp tool." },
            { "Zmień folder…", "Change folder…" },
            { "Gdzie zapisać film?", "Where to save the video?" },
            { "Zapisz w:", "Save to:" },
            { "Na wierzchu", "On top" },
            { "▣ Film na wierzchu (małe okienko)", "▣ Video on top (small window)" },
            { "Film na wierzchu", "Video on top" },
            { "Zamknij film", "Close video" },
            { "Wróć do karty (otwórz stronę w Velivo)", "Back to a tab (open the page in Velivo)" },
            { "Przeciągnij, aby przesunąć · kółko myszy: przezroczystość", "Drag to move · mouse wheel: transparency" },
            { "Zawsze na wierzchu: WŁĄCZONE – kliknij, aby okienko mogło schować się pod inne", "Always on top: ON – click to let the window go behind others" },
            { "Zawsze na wierzchu: wyłączone – kliknij, aby przypiąć nad wszystkim", "Always on top: off – click to pin above everything" },
            { "Importuj z Chrome/Edge/Brave…", "Import from Chrome/Edge/Brave…" },
            { "Przenieś zakładki i hasła z innej przeglądarki", "Move bookmarks and passwords from another browser" },
            { "1. Zakładki – Velivo odczyta je samo", "1. Bookmarks – Velivo reads them by itself" },
            { "Nie znaleziono zakładek Chrome, Edge, Brave, Opery ani Vivaldi na tym komputerze.", "No Chrome, Edge, Brave, Opera or Vivaldi bookmarks were found on this computer." },
            { "Importuj zaznaczone zakładki", "Import selected bookmarks" },
            { "Nic nowego – te zakładki już są w Velivo.", "Nothing new – these bookmarks are already in Velivo." },
            { "2. Hasła – przez plik CSV (2 minuty)", "2. Passwords – via a CSV file (2 minutes)" },
            { "Przeglądarki szyfrują hasła tak, że żaden inny program nie może ich odczytać – to dla Twojego bezpieczeństwa. Dlatego hasła trzeba raz wyeksportować do pliku:", "Browsers encrypt passwords so no other program can read them – for your safety. So passwords must be exported to a file once:" },
            { "a) kliknij „Otwórz eksport haseł” poniżej (otworzy się tamta przeglądarka),\nb) wybierz „Eksportuj hasła” i zapisz plik,\nc) wróć tu i kliknij „Wczytaj plik CSV…”,\nd) usuń plik CSV – hasła są w nim zapisane zwykłym tekstem.", "a) click “Open password export” below (that browser will open),\nb) choose “Export passwords” and save the file,\nc) come back here and click “Load CSV file…”,\nd) delete the CSV file – the passwords are stored in it as plain text." },
            { "Wczytaj plik CSV…", "Load CSV file…" },
            { "Logowania do stron (np. konto Google) nie przenoszą się – zaloguj się raz w Velivo, a Velivo je zapamięta.", "Site logins (e.g. a Google account) don't transfer – sign in once in Velivo and Velivo will remember it." },
            { "Import z innej przeglądarki", "Import from another browser" },
            { "Ważne: zrób import, ZANIM odinstalujesz starą przeglądarkę – po jej usunięciu zakładek nie da się odczytać, a haseł wyeksportować. Hasła zapisane na koncie Google można też później pobrać ze strony passwords.google.com.", "Important: import BEFORE you uninstall the old browser – once it is removed, its bookmarks can't be read and its passwords can't be exported. Passwords saved in a Google account can also be downloaded later from passwords.google.com." },
            { "📥 Import haseł, loginów i zakładek", "📥 Import passwords, logins and bookmarks" },
            { "🔑 Hasła i loginy z pliku (CSV: KeePassXC, Chrome, Edge…)", "🔑 Passwords and logins from a file (CSV: KeePassXC, Chrome, Edge…)" },
            { "🌐 Z Chrome / Edge / Brave / Opery", "🌐 From Chrome / Edge / Brave / Opera" },
            { "Wpisz zapisany login i hasło z Velivo", "Fill in the saved login and password from Velivo" },
            { "Wpisz", "Fill in" },
            { "Wygeneruj silne hasło", "Generate a strong password" },
            { "Generuj", "Generate" },
            { "Inne konto z bazy Velivo…", "Another account from the Velivo vault…" },
            { "Szukaj konta (nazwa, adres albo e-mail):", "Search for an account (name, address or e-mail):" },
            { "Wybierz konto do wpisania", "Choose an account to fill in" },
            { "Zmieniono", "Changed" },
            { "Wykryto dane konta bankowego.", "Bank account details detected." },
            { "Konto bankowe", "Bank account" },
            { "Strona: ", "Site: " },
            { "Upewnij się, że to prawdziwa strona tego konta – oszuści podrabiają adresy (np. faceb00k.com).", "Make sure this is the real site of this account – scammers fake addresses (e.g. faceb00k.com)." },
            { "dane karty", "card details" },
            { "dane konta bankowego", "bank account details" },
            { "Wpisać ", "Fill in " },
            { " na stronie:", " on the site:" },
            { "Upewnij się, że to prawdziwy sklep lub bank.", "Make sure this is the real shop or bank." },
            { "Wykrywaj fałszywe strony banków, sklepów i portali (działa bez internetu)", "Detect fake bank, shop and portal sites (works offline)" },
            { "Ostrzega przed adresami typu paypa1.com, ebay-weryfikacja.top i podróbkami stron, do których masz zapisane hasła.", "Warns about addresses like paypa1.com, ebay-verify.top and fakes of sites you have saved passwords for." },
            { "Zawsze szyfrowane połączenie (HTTPS) – ostrzegaj przed stronami bez szyfrowania", "Always encrypted connection (HTTPS) – warn about unencrypted sites" },
            { "Bezpieczne płatności – na stronach banków i płatności ukrywaj okno przed programami nagrywającymi ekran", "Safe payments – on bank and payment sites hide the window from screen-recording programs" },
            { "Chroni przed złośliwymi programami, które podglądają ekran. Na tych stronach nie zrobisz też zrzutu ekranu.", "Protects against malware that spies on the screen. You also can't take screenshots on these sites." },
            { "Ta strona nie obsługuje szyfrowania (HTTPS):", "This site does not support encryption (HTTPS):" },
            { "Wszystko, co tu wpiszesz, może zostać podejrzane po drodze. Nie wpisuj haseł, danych karty ani adresu.", "Anything you type here can be intercepted on the way. Don't enter passwords, card details or your address." },
            { "Otworzyć mimo to?", "Open anyway?" },
            { "Brak szyfrowania", "No encryption" },
            { "Adres zawiera znaki z innych alfabetów, które udają zwykłe litery.", "The address contains characters from other alphabets that imitate normal letters." },
            { "Adres udaje stronę:", "The address imitates the site:" },
            { "ale NIE należy do tej firmy.", "but does NOT belong to that company." },
            { "Uwaga – to może być fałszywa strona!", "Warning – this may be a fake site!" },
            { "Oszuści podrabiają strony banków, sklepów i portali, żeby ukraść hasło, kartę lub pieniądze. Nie wpisuj tu żadnych danych.", "Scammers fake bank, shop and portal sites to steal passwords, cards or money. Don't enter any data here." },
            { "Otworzyć mimo to? (wybierz Nie, jeśli nie masz pewności)", "Open anyway? (choose No if you are not sure)" },
            { "Ochrona przed oszustwem", "Fraud protection" },
            { "🛡 Bezpieczne płatności: okno Velivo jest niewidoczne dla programów nagrywających ekran.", "🛡 Safe payments: the Velivo window is invisible to screen-recording programs." },
            { "uBlock Origin Lite – wbudowany bloker reklam (zalecany)", "uBlock Origin Lite – built-in ad blocker (recommended)" },
            { "Dodatek open source (GPL-3.0) dołączony do Velivo. Działa razem z blokadą Velivo.", "Open-source add-on (GPL-3.0) bundled with Velivo. Works together with Velivo's blocking." },
            { "🛡 uBlock Origin Lite jest wbudowany na stałe – wyniki widać na tarczy.", "🛡 uBlock Origin Lite is permanently built in – its results show on the shield." },
            { "Wbudowany w Velivo, wyniki widać na tarczy. Możesz go wyłączyć.", "Built into Velivo, its results show on the shield. You can turn it off." },
            { "Ustawienia uBlock Origin Lite…", "uBlock Origin Lite settings…" },
            { "uBlock Origin Lite nie jest włączony.", "uBlock Origin Lite is not enabled." },
            { "🔊 Wybierz głośniki dla Velivo…", "🔊 Choose speakers for Velivo…" },
            { "Przy „Velivo” lub „Microsoft Edge WebView2” wybierz swoje głośniki zamiast „Domyślne” – Windows zapamięta to na stałe.", "Next to “Velivo” or “Microsoft Edge WebView2” choose your speakers instead of “Default” – Windows remembers it permanently." },
            { "Gdy inny program przełącza dźwięk Velivo na inne głośniki – przypnij Velivo do swoich głośników.", "When another program moves Velivo's sound to other speakers – pin Velivo to your speakers." },
            { "Głośniki Velivo:", "Velivo speakers:" },
            { "Domyślne wyjście Windows", "Windows default output" },
            { "Nie gub dźwięku: gdy program muzyczny (Ableton, Cubase) zajmie głośniki, graj na innym aktywnym wyjściu i wróć po ich zwolnieniu", "Don't lose sound: when a music program (Ableton, Cubase) takes the speakers, play on another active output and return when they are free" },
            { "🔊 Mikser głośności Windows…", "🔊 Windows volume mixer…" },
            { "Dźwięk Velivo: ", "Velivo sound: " },
            { "domyślne wyjście Windows", "Windows default output" },
            { "Płynne przejście między stronami:", "Smooth transition between pages:" },
            { "Naturalne (silnik Edge)", "Natural (Edge engine)" },
            { "Szybkie rozjaśnienie (0,15 s)", "Quick fade-in (0.15 s)" },
            { "Delikatne rozjaśnienie (0,3 s)", "Gentle fade-in (0.3 s)" },
            { "Wolne rozjaśnienie (0,5 s)", "Slow fade-in (0.5 s)" },
            { "Po zamknięciu okna zostań w zasobniku (synchronizacja w tle, natychmiastowy start)", "Stay in the system tray when the window is closed (background sync, instant start)" },
            { "Ikonka Velivo przy zegarze pulsuje podczas synchronizacji. Prawy przycisk na ikonce: Otwórz, Synchronizuj teraz, Zamknij całkowicie.", "The Velivo icon by the clock pulses while syncing. Right-click the icon: Open, Sync now, Exit completely." },
            { "Velivo działa w zasobniku i synchronizuje się w tle. Kliknij ikonkę, aby otworzyć.", "Velivo is running in the tray and syncing in the background. Click the icon to open it." },
            { "Otwórz Velivo", "Open Velivo" },
            { "Synchronizuj teraz", "Sync now" },
            { "Zamknij Velivo całkowicie", "Exit Velivo completely" },
            { "Velivo – synchronizacja…", "Velivo – syncing…" },
            { "Wygląd czytnika", "Reader look" },
            { "☀ Jasny", "☀ Light" },
            { "🌙 Ciemny", "🌙 Dark" },
            { "🌅 Nocny", "🌅 Night" },
            { "Natężenie trybu nocnego", "Night mode strength" },
            { "🕶 Otwórz jako prywatną (incognito)", "🕶 Open as private (incognito)" },
            { "Spokojne rozjaśnienie (1 s)", "Calm fade-in (1 s)" },
            { "Bardzo spokojne (2 s)", "Very calm (2 s)" },
            { "Senne (3 s)", "Dreamy (3 s)" },
            { "Najwolniejsze (4 s)", "Slowest (4 s)" },
            { "Efekt wejścia treści:", "Content entrance effect:" },
            { "Wysunięcie z wyostrzeniem (jak Gemini)", "Slide up with focus (like Gemini)" },
            { "Wyostrzenie", "Focus in" },
            { "Delikatne przybliżenie", "Gentle zoom" },
            { "Brak", "None" },
            // ---- ustawienia: jezyk ----
            { "Język interfejsu / Language:", "Language / Język interfejsu:" },
            { "Automatycznie (język z instalatora / Windows)", "Automatic (installer / Windows language)" },
            { "Zmiana języka zadziała po ponownym uruchomieniu Velivo.", "The language change takes effect after restarting Velivo." },
            // ---- tryb bankowy ----
            { "Anulowano albo nie dotknięto klucza na czas.", "Cancelled, or the key was not touched in time." },
            { "Dodaj co najmniej jeden klucz albo odznacz opcję klucza.", "Add at least one key or untick the key option." },
            { "Dodaj kartę:", "Add a card:" },
            { "Dodatkowo wymagaj klucza sprzętowego (YubiKey, Google Titan…)", "Also require a hardware security key (YubiKey, Google Titan…)" },
            { "Dotknij klucza sprzętowego (okienko Windows)…", "Touch your security key (Windows dialog)…" },
            { "Hasła się różnią.", "Passwords do not match." },
            { "Hasło (min. 8 znaków):", "Password (min. 8 characters):" },
            { "Hasło musi mieć co najmniej 8 znaków.", "The password must have at least 8 characters." },
            { "Imię i nazwisko na karcie:", "Name on card:" },
            { "Klucz sprzętowy: błąd ", "Security key: error " },
            { "Kodu CVV nie zapisujemy – wpiszesz go sam przy płatności.", "The CVV is never saved – you type it yourself when paying." },
            { "Najpierw otwórz tryb bankowy (hasłem / kluczem)", "Open banking mode first (password / key)" },
            { "Nazwa (np. Visa PKO):", "Name (e.g. My Visa):" },
            { "Nie dodano jeszcze żadnego klucza.", "No key added yet." },
            { "Nie udało się odczytać kart.", "Could not read the cards." },
            { "Nie wykryto klucza na USB (klucz NFC/Bluetooth Windows znajdzie sam po kliknięciu „Dodaj”).", "No USB key detected (Windows will find an NFC/Bluetooth key after you click “Add”)." },
            { "Nieprawidłowy numer karty.", "Invalid card number." },
            { "Nowe hasło (puste = bez zmiany):", "New password (empty = unchanged):" },
            { "Numer karty:", "Card number:" },
            { "Osobny, odizolowany profil na banki i zakupy: własne logowania i ciasteczka, bez dodatków, bez historii. Blokuje się po 10 minutach bezczynności.", "A separate, isolated profile for banking and shopping: its own logins and cookies, no extensions, no history. Locks after 10 minutes of inactivity." },
            { "Po haśle Windows poprosi o klucz sprzętowy.", "After the password Windows will ask for your security key." },
            { "Podaj hasło trybu bankowego:", "Enter the banking mode password:" },
            { "Powtórz hasło:", "Repeat password:" },
            { "Sprawdzam klucz sprzętowy…", "Checking for a security key…" },
            { "Ten klucz jest już dodany.", "This key is already added." },
            { "Ten klucz nie jest dodany do trybu bankowego.", "This key is not registered for banking mode." },
            { "Ten klucz nie obsługuje wymaganego podpisu (ES256).", "This key does not support the required signature (ES256)." },
            { "Tryb bankowy", "Banking mode" },
            { "Tryb bankowy Velivo", "Velivo banking mode" },
            { "Tryb bankowy wyczyszczony", "Banking mode cleared" },
            { "Tryb bankowy – odizolowany, chroniony hasłem (i kluczem sprzętowym)\nPrawy klik: ustawienia i blokada", "Banking mode – isolated, protected by password (and security key)\nRight-click: settings and lock" },
            { "Tryb bankowy – ustawienia", "Banking mode – settings" },
            { "Usunąć hasło i klucze trybu bankowego oraz wyczyścić jego dane (logowania, ciasteczka)?\nUstawisz go od nowa.", "Remove the banking mode password and keys and clear its data (logins, cookies)?\nYou will set it up again." },
            { "Usuń wszystkie klucze", "Remove all keys" },
            { "Usuń zaznaczoną", "Remove selected" },
            { "Ważna do (MM/RR):", "Expires (MM/YY):" },
            { "Włóż klucz sprzętowy – będzie potrzebny po haśle.", "Insert your security key – it is needed after the password." },
            { "Zapomniałem hasła – wyczyść tryb bankowy…", "Forgot password – clear banking mode…" },
            { "Złe hasło.", "Wrong password." },
            { "⚙ Ustawienia trybu bankowego…", "⚙ Banking mode settings…" },
            { "✔ Wykryto podłączony klucz sprzętowy.", "✔ A security key is connected." },
            { "➕ Dodaj", "➕ Add" },
            { "➕ Dodaj klucz (włóż go i dotknij)", "➕ Add key (insert and touch it)" },
            { "🏦 Bankowa", "🏦 Banking" },
            { "🏦 Tryb bankowy zapisany", "🏦 Banking mode saved" },
            { "💳 Karty zapisane (zaszyfrowane)", "💳 Cards saved (encrypted)" },
            { "💳 Moje karty", "💳 My cards" },
            { "💳 Moje karty…", "💳 My cards…" },
            { "💳 Wpisano dane karty – CVV wpisz sam", "💳 Card details filled in – type the CVV yourself" },
            { "💳 Wypełnij kartę na tej stronie", "💳 Fill in a card on this page" },
            { "🔒 Tryb bankowy zablokowany", "🔒 Banking mode locked" },
            { "🔒 Tryb bankowy zablokowany po 10 minutach bezczynności", "🔒 Banking mode locked after 10 minutes of inactivity" },
            { "🔒 Zablokuj teraz", "🔒 Lock now" },
            { "Ten klucz otwiera tryb, ale nie odszyfrowuje kart – użyj klucza, który szyfruje karty", "This key opens the mode but cannot decrypt the cards – use a key that encrypts them" },
            { "Karty są zamknięte – otwórz tryb bankowy kluczem, który szyfruje karty, i wtedy zmień ustawienia.", "The cards are locked – open banking mode with a key that encrypts them, then change the settings." },
            { "\n🔐 = klucz szyfruje karty (bez niego karty się nie otworzą)", "\n🔐 = the key encrypts the cards (they won't open without it)" },
            { "Dotknij klucza jeszcze raz – przygotowanie szyfrowania kart…", "Touch the key again – setting up card encryption…" },
            { "Ten klucz nie potrafi szyfrować – będzie tylko otwierał tryb bankowy.", "This key cannot encrypt – it will only open banking mode." },
            { "🔒 Tryb bankowy zmieniony na innym komputerze – otwórz go ponownie", "🔒 Banking mode changed on another computer – open it again" },
            { "📝 Notatki (loginy, hasła, numery klienta)…", "📝 Notes (logins, passwords, customer numbers)…" },
            { "🔖 Moje strony bankowe i sklepy", "🔖 My banking and shopping sites" },
            { "➕ Dodaj tę stronę do moich stron bankowych", "➕ Add this site to my banking sites" },
            { "Otwórz tryb bankowy, aby zobaczyć listę", "Open banking mode to see the list" },
            { "(pusto – otwórz stronę w karcie bankowej i wybierz „Dodaj tę stronę”)", "(empty – open a site in a banking tab and choose “Add this site”)" },
            { "Usuń stronę z listy", "Remove a site from the list" },
            { "Ta strona już jest na liście", "This site is already on the list" },
            { "🔖 Dodano do moich stron bankowych: ", "🔖 Added to my banking sites: " },
            { "🏦 To Twoja strona bankowa – bezpieczniej otworzyć ją w trybie bankowym (przycisk 🏦)", "🏦 This is one of your banking sites – it is safer to open it in banking mode (🏦 button)" },
            { "📝 Notatki trybu bankowego", "📝 Banking mode notes" },
            { "Tytuł (np. Bank – login):", "Title (e.g. Bank – login):" },
            { "Treść (login, hasło, numer klienta…):", "Content (login, password, customer number…):" },
            { "➕ Dodaj nową", "➕ Add new" },
            { "✔ Zmień zaznaczoną", "✔ Update selected" },
            { "📋 Kopiuj treść", "📋 Copy content" },
            { "📋 Skopiowano – schowek wyczyści się za 30 s", "📋 Copied – the clipboard will be cleared in 30 s" },
            { "Notatka", "Note" },
            { "📝 Notatki zapisane (zaszyfrowane)", "📝 Notes saved (encrypted)" },
            { "🔑 Otwórz kluczem sprzętowym", "🔑 Open with security key" },
            { "Nie masz klucza? Podaj hasło:", "No key? Enter the password:" },
            { "Otwórz hasłem", "Open with password" },
            { "Ten klucz jeszcze nie otwiera trybu sam – podaj raz hasło (z kluczem), potem wystarczy sam klucz.", "This key cannot open the mode on its own yet – enter the password once (with the key), then the key alone is enough." },
            { "🔑 Od teraz ten klucz sam otwiera tryb bankowy (inne klucze: otwórz nimi raz z hasłem)", "🔑 From now on this key alone opens banking mode (other keys: open once with them and the password)" },
            { "Nie wykryto klucza – włóż go i kliknij przycisk albo podaj hasło.", "No key detected – insert it and click the button, or enter the password." },
            { "Kliknij przycisk i dotknij klucza albo podaj hasło.", "Click the button and touch the key, or enter the password." },
            { "➕ Dodaj bank lub sklep (nazwa i adres)…", "➕ Add a bank or shop (name and address)…" },
            { "🔖 Dodaj bank lub sklep", "🔖 Add a bank or shop" },
            { "Nazwa (np. mBank, Allegro):", "Name (e.g. My bank, Amazon):" },
            { "Adres strony (np. https://www.mbank.pl):", "Website address (e.g. https://www.mybank.com):" },
            { "Nieprawidłowy adres strony.", "Invalid website address." },
            { "🏦 Moje banki", "🏦 My banks" },
            { "🛒 Moje sklepy online", "🛒 My online shops" },
            { "➕ Dodaj tę stronę do Moich banków", "➕ Add this site to My banks" },
            { "➕ Dodaj tę stronę do Moich sklepów", "➕ Add this site to My shops" },
            { "➕ Dodaj sklep (nazwa i adres)…", "➕ Add a shop (name and address)…" },
            { "➕ Dodaj bank (nazwa i adres)…", "➕ Add a bank (name and address)…" },
            { "🛒 Dodaj sklep online", "🛒 Add an online shop" },
            { "🏦 Dodaj bank", "🏦 Add a bank" },
            { "🛒 Dodano do Moich sklepów: ", "🛒 Added to My shops: " },
            { "🏦 Dodano do Moich banków: ", "🏦 Added to My banks: " },
            { "(pusto)", "(empty)" },
            { "📝 Moje notatki (loginy, hasła, numery klienta)", "📝 My notes (logins, passwords, customer numbers)" },
            { "Główny", "Main" },
            { "Tryb bankowy – wybierz profil", "Banking mode – choose a profile" },
            { "Czyj tryb bankowy otworzyć?", "Whose banking mode should be opened?" },
            { "Nowy profil bankowy", "New banking profile" },
            { "Nazwa profilu (np. imię drugiego użytkownika):", "Profile name (e.g. the other user's name):" },
            { "Każdy profil ma własne hasło lub klucz, osobne logowania w bankach i osobne karty, banki, sklepy i notatki.", "Each profile has its own password or key, separate bank logins and separate cards, banks, shops and notes." },
            { "👤 Profile bankowe", "👤 Banking profiles" },
            { "➕ Nowy profil bankowy (inny użytkownik)…", "➕ New banking profile (another user)…" },
            { "🔒 Tryb bankowy zablokowany po bezczynności", "🔒 Banking mode locked after inactivity" },
            { "\n🔐 = klucz sam otwiera tryb i szyfruje bazę (hasło działa zapasowo)", "\n🔐 = the key alone opens the mode and encrypts the vault (the password works as a backup)" },
            { "Zablokuj po bezczynności:", "Lock after inactivity:" },
            { "Osobny, odizolowany profil na banki i zakupy: własne logowania i ciasteczka, bez dodatków, bez historii. Blokuje się sam po bezczynności.", "A separate, isolated profile for banking and shopping: its own logins and cookies, no extensions, no history. Locks itself after inactivity." },
            { "🔍 Szukaj w mojej bazie…", "🔍 Search my vault…" },
            { "🔑 Wpisz login z notatki na tej stronie", "🔑 Fill in a login from a note on this page" },
            { "💾 Kopia zapasowa bazy…", "💾 Back up the vault…" },
            { "📂 Przywróć bazę z kopii…", "📂 Restore the vault from a backup…" },
            { "📜 Dziennik otwarć…", "📜 Access log…" },
            { "Kategoria:", "Category:" },
            { "Login", "Login" },
            { "PIN", "PIN" },
            { "Przelewy", "Transfers" },
            { "Kody odzyskiwania", "Recovery codes" },
            { "Inne", "Other" },
            { "🎲 Wygeneruj hasło", "🎲 Generate password" },
            { "hasło: ", "password: " },
            { "🎲 Wygenerowano mocne hasło (skopiowane – schowek wyczyści się za 30 s)", "🎲 Strong password generated (copied – the clipboard will be cleared in 30 s)" },
            { "📜 Dziennik otwarć trybu bankowego", "📜 Banking mode access log" },
            { "kluczem", "with key" },
            { "hasłem", "with password" },
            { "✔ otwarto", "✔ opened" },
            { "✖ złe hasło", "✖ wrong password" },
            { "karta wygasła", "card expired" },
            { "wygasa ", "expires " },
            { "🔍 Szukaj w mojej bazie", "🔍 Search my vault" },
            { "💾 Zapisano kopię zapasową (zaszyfrowaną)", "💾 Backup saved (encrypted)" },
            { "To nie jest kopia trybu bankowego.", "This is not a banking mode backup." },
            { "Przywrócić tryb bankowy z kopii? Obecne dane trybu bankowego zostaną zastąpione.", "Restore banking mode from the backup? The current banking mode data will be replaced." },
            { "📂 Przywrócono tryb bankowy z kopii", "📂 Banking mode restored from the backup" },
            { "🔑 Wpisano dane logowania z notatki", "🔑 Login details filled in from the note" },
            { "⚠ UWAGA: ta strona może podszywać się pod ", "⚠ WARNING: this site may be impersonating " },
            { "Otwarta strona: ", "Opened site: " },
            { "Twoja prawdziwa strona: ", "Your real site: " },
            { "Nie wpisuj tu loginu, hasła ani danych karty. Otwórz bank z listy „Moje banki”.", "Do not enter your login, password or card details here. Open your bank from “My banks”." },
            { "🛡 Tryb bankowy: okno Velivo jest niewidoczne dla zrzutów i nagrywania ekranu.", "🛡 Banking mode: the Velivo window is hidden from screenshots and screen recording." },
            { "❓ Instrukcja trybu bankowego", "❓ Banking mode guide" },
        };
    }
}
